### ISSUE TITLE
u16 for header fields in a packet should trigger an error

### ISSUE THREAD

**Issue by little-dude** [libpnet/libpnet#128]
From https://github.com/libpnet/libpnet/pull/89#issuecomment-158792770
Compiler should not accept `u16` attribute fields in a packet. Only  `u16be` or `u16le` are accepted. 

```rust
#[packet]
pub struct MyPacket {
   a_field: u16,  // should be refused
}
```

**Comment by mrmonday** [comment]
I never can remember the format for commit messages to make this happen automatically... Fixed now though!
