### ISSUE TITLE
Parse complete frame

### ISSUE THREAD

**Issue by Yamakaky** [libpnet/libpnet#235]
For now, we have only things like "bytes -> Ethernet", where the payload is not decoded. It would be cool to be able to decode an Ethernet frame and automatically have the ip and tcp layers decoded.

**Comment by mrmonday** [comment]
I believe this falls under the umbrella of #139.

It's worth talking to @faern about this, since he's working on a TCP/IP stack and likely has a good insight about the nicest way to do this.

**Comment by Yamakaky** [comment]
I think the ethernet packet could have a field with type `Result<Parsed, Raw>` for example. That way, you can always parse yourself if the auto-parse fails.

**Comment by mrmonday** [comment]
That doesn't really work with libpnet's model - it doesn't actually do any parsing, it just does some bit twiddling, regardless of what's there.

It would also require adding domain-specific knowledge to libpnet, which I'm not sure is appropriate. I would favour introducing an abstraction which enables definitions of relationships between packets instead, but I haven't put much thought into how that would work in Rust.

**Comment by faern** [comment]
I think this feature is out of scope for pnet. I much rather keep the packet part of pnet as simple as it is, it should not have domain knowledge of what the fields in the packets actually mean. Keep all actual parsing and decisions on what to do with the payload up to the user of pnet.

You can implement this quite easily yourself my just matching on the `ethertype` etc.

If you really want this feature I would say it would suite much better in a separate crate where you can provide a parse-interface that takes a `&[u8]` and returns some kind of linked structure with the packets at different levels.

**Comment by Yamakaky** [comment]
Ok, thanks.
