### ISSUE TITLE
pnet_macros can't be compiled w/ Rust 1.14.0 and Cargo 0.15.0-nightly

### ISSUE THREAD

**Issue by tfukushima** [libpnet/libpnet#238]
Hi libpnet devs,

Happy New Year. 🎉 🎍  In my hobby project during holidays, I tried to use libpnet as follow.

```
$ cat Cargo.toml
[package]
name = "hello-libpnet"
version = "0.1.0"
authors = ["Taku Fukushima <___@gmail.com>"]

[dependencies]
# pcap = "0.5.7"   # I wanted to use pcap as well but I just commented it out for simplicity.
pnet = "0.14.0"
```

Then I ran `cargo build` and I got the following compile errors for pnet_macros. I'm not 100% sure but it looks like the APIs of regex changed and it caused the compile errors? I tried building my project on MacOSX 10.11.6 and Linux (Amazon Linux; 4.4.16-27.56.amzn1.x86_64 ), and got the same errors. I might be missing something and I'd really appreciate if you could point that out.

```
$ cargo clean
$ cargo build
   Compiling void v1.0.2
   Compiling rustc-serialize v0.3.22
   Compiling utf8-ranges v1.0.0
   Compiling libc v0.2.18
   Compiling bitflags v0.5.0
   Compiling pnet_macros_support v0.1.1
   Compiling syntex_pos v0.42.0
   Compiling winapi-build v0.1.1
   Compiling ws2_32-sys v0.2.1
   Compiling winapi v0.2.8
   Compiling log v0.3.6
   Compiling kernel32-sys v0.2.2
   Compiling thread-id v3.0.0
   Compiling unicode-xid v0.0.3
   Compiling term v0.4.4
   Compiling syntex_errors v0.42.0
   Compiling syntex_syntax v0.42.0
   Compiling syntex v0.42.2
   Compiling memchr v0.1.11
   Compiling aho-corasick v0.5.3
   Compiling memchr v1.0.0
   Compiling unreachable v0.1.1
   Compiling thread_local v0.3.2
   Compiling regex-syntax v0.4.0
   Compiling regex v0.2.0
   Compiling pnet_macros v0.11.0
error: no method named `at` found for type `regex::Captures<'_>` in the current scope
    --> /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/pnet_macros-0.11.0/src/decorator.rs:1065:25
     |
1065 |         let size = iter.at(1).unwrap();
     |                         ^^

error: no method named `at` found for type `regex::Captures<'_>` in the current scope
    --> /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/pnet_macros-0.11.0/src/decorator.rs:1066:59
     |
1066 |         let (endianness, has_end) = if let Some(e) = iter.at(2) {
     |                                                           ^^

error: aborting due to 2 previous errors

error: Could not compile `pnet_macros`.

To learn more, run the command again with --verbose.
```

I installed Rust w/ rustup and the versions of Rust and Cargo are below:

```
$ rustc --version
rustc 1.14.0 (e8a012324 2016-12-16)
$ cargo --version
cargo 0.15.0-nightly (298a012 2016-12-20)
```

**Comment by BurntSushi** [comment]
The problem is that the [`pnet_macros` crate has a liberal dependency on `regex`](https://github.com/libpnet/libpnet/blob/2875d923b034ed28e54165fd65d3072f59c7c3f0/pnet_macros/Cargo.toml#L40). The fix is to either update `pnet_macros` to use `0.1` instead of `>=0.1`, or to upgrade to using `0.2` proper.

**Comment by mrmonday** [comment]
Thanks for the detailed report.

I've fixed the dependency (so hopefully this doesn't happen in future), and also upgraded the version of the regex crate we depend on.

Hopefully I'll get a new release of pnet_macros out tonight - we'll see how long CI takes.

**Comment by mrmonday** [comment]
This should hopefully be fixed now, I've published a new version of pnet_macros - https://crates.io/crates/pnet_macros/0.12.0

**Comment by tfukushima** [comment]
@mrmonday @BurntSushi Thanks for the quick fix. I could build libpnet with `cargo update`.

BTW, as you must know, libpnet 0.14.0 can't be built with Rust >=0.12.0. So I specified the commit that you made and I could build my project.

```
[package]
name = "hello-libpnet"
version = "0.1.0"
authors = ["Taku Fukushima <___@gmail.com>"]

[dependencies]
pcap = "0.5.7"
pnet = {git = "https://github.com/libpnet/libpnet.git", rev = "ae6ce01b36911479742fb20e95daab4bd0b31752"}
```

Have nice holidays!

**Comment by mrmonday** [comment]
Are you using nightly?

libpnet compiles and passes tests for OS X, Linux, and Windows using Rust versions:

 * 1.11.0
 * 1.14.0
 * 1.15.0-beta.2

See:
 * https://travis-ci.org/libpnet/libpnet
 * https://ci.appveyor.com/project/mrmonday/libpnet

I've just published v0.15.0 of libpnet - https://crates.io/crates/pnet/0.15.0 - with any luck that fixes it.

**Comment by tfukushima** [comment]
@mrmonday Oh, I wrote "libpnet can't be built" but that's not true. What I meant was that it could be compiled by itself but when I added `libpnet = "0.14.0"` in the dependencies of `Cargo.toml` I got a bunch of compile errors.

Thanks for publishing the new version and now I don't have to specify the rev number in the dependences. I'm using stable and my project is now perfectly compiled. 👍

**Comment by BurntSushi** [comment]
@tfukushima Note that you should definitely be specifying rev numbers. A `*` dependency is generally frowned upon (and crates.io will disallow it) because it will automatically bring in semver incompatible releases.
