### ISSUE TITLE
How to run tests in pnet_macros?

### ISSUE THREAD

**Issue by polachok** [libpnet/libpnet#241]
I got some time to write tests for https://github.com/libpnet/libpnet/pull/208.
First attempt:

```
libpnet/pnet_macros# cargo test --features=with-syntex
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling pnet v0.15.0 (file:///usr/src/pnetlink/libpnet)
   Compiling pnet_macros_plugin v0.1.0 (file:///usr/src/pnetlink/libpnet/pnet_macros_plugin)
error[E0308]: mismatched types
  --> /usr/src/pnetlink/libpnet/pnet_macros_plugin/src/lib.rs:15:27
   |
15 |     pnet_macros::register(registry);
   |                           ^^^^^^^^ expected struct `syntex::Registry`, found struct `rustc_plugin::Registry`
   |
   = note: expected type `&mut syntex::Registry`
   = note:    found type `&mut rustc_plugin::Registry<'_>`

error: aborting due to previous error
```

And without syntex I get:

```
libpnet/pnet_macros# cargo test 
   Compiling pnet_macros v0.12.0 (file:///usr/src/pnetlink/libpnet/pnet_macros)
error[E0532]: expected tuple struct/variant, found unit variant `ast::MetaItemKind::Word`
   --> src/decorator.rs:134:17
    |
134 |                 ast::MetaItemKind::Word(ref s) => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^ not a tuple struct/variant

error[E0532]: expected tuple struct/variant, found unit variant `ast::MetaItemKind::Word`
   --> src/decorator.rs:157:36
    |
157 |                             if let ast::MetaItemKind::Word(ref s) = ty.node {
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^ not a tuple struct/variant

error[E0433]: failed to resolve. Could not find `InternedString` in `token`
   --> src/lib.rs:179:25
    |
179 |     ecx.meta_word(span, token::InternedString::new(word))
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `InternedString` in `token`

error[E0433]: failed to resolve. Could not find `InternedString` in `token`
   --> src/lib.rs:202:42
    |
202 |                                          token::InternedString::new("derive"),
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `InternedString` in `token`

```

I'm on nighly.

**Comment by mrmonday** [comment]
Unless `compiletest_rs` has been updated to work with syntex, you need a nightly version of Rust to run the tests.

The version of the Rust nightly needs to match the version of syntex that we're using. libpnet currently uses syntex `0.42.*`, which was released on August 19/20, 2016. That means you need a version of nightly from last August to run the tests.

Alternatively, if libpnet is updated to the latest version of syntex, then you could use a current nightly - until there's a new version...

It's an unfortunate situation - I'd like to get away from using compiler plugins, there are too many hacks involved to get them working.

**Comment by polachok** [comment]
>libpnet currently uses syntex 0.42.*, which was released on August 19/20, 2016. That means you need a version of nightly from last August to run the tests.

Thanks for the explanation, I see now.

>It's an unfortunate situation - I'd like to get away from using compiler plugins, there are too many hacks involved to get them working.

Would [macros 1.1](https://github.com/rust-lang/rfcs/blob/master/text/1681-macros-1.1.md) help? It seems like they are on the fast track to stabilization.

**Comment by mrmonday** [comment]
I haven't had time to read the full RFC, it looks like they'd probably work for what we currently have though, yes.

I don't know how much work it would be to convert the existing pnet_macros across.
