### ISSUE TITLE
Consider splitting packet parsers into a separate crate

### ISSUE THREAD

**Issue by moosingin3space** [libpnet/libpnet#246]
For instance, the way `serde` does it (`serde` for core functionality, `serde_json` for serializing JSON data, etc) might not be a bad idea. A brief design:

- `pnet` and `pnet_macros` stay mostly the way they are, except with the `backend` module removed and replaced with a `Backend` trait or similar.
- `pnet_linux`, `pnet_netmap`, `pnet_bpf`, `pnet_pcap`, and `pnet_windows` crates provide backends.
- A crate called `pnet_crossplatform_defaults` or similar could implement `Backend` by proxying to the `pnet_linux`, `pnet_bpf`, and `pnet_windows` crates.

Thoughts?

**Comment by moosingin3space** [comment]
If backends are split, it becomes easier for a developer to choose a specific backend or use multiple backends in the same application. Cargo features seem a little clunky for this -- what if I want to use `pnet` to write a `tcpreplay` replacement? With separated backends, once could write code like:

```rust
let mut input = match pnet_pcap::from_file("/path/to/input.pcap") {
  Ok(Ethernet(_, rx)) => rx,
  _ => panic!("must be ethernet")
};

let iface = pnet_netmap::from_iface_name("re0");
let mut output = match pnet_netmap::from_iface(iface) {
  Ok(Ethernet(tx, _)) => tx,
  _ => panic!("must be ethernet")
};

let mut pkts = input.iter();
loop {
  match pkts.next() {
    Ok(packet) {
      tx.send_to(packet, iface);
    }
  }
}
```

where multiple backends are used in tandem. 

Separating out the packet handlers would also be a good idea. I'm interested in other ideas for modularizing libpnet too.

**Comment by mrmonday** [comment]
This is no easier than the current situation:
```rust
use pnet::datalink::dummy;
use pnet::datalink::netmap;

let chan1 = dummy::channel(some_ni, Default::default());
let chan2 = netmap::channel(some_ni2, Default::default());

. . . etc . . .
```
I don't buy the features being clunky argument, it's the difference between:
```toml
[dependencies.pnet]
version = "1.0.*"
features = ["netmap"]
```
and
```toml
[dependencies]
pnet = "1.0.*"
pnet_netmap="1.0.*"
```
In the latter case there are two versions to keep in sync, rather than one.

**Comment by moosingin3space** [comment]
I was unaware that multiple backends were usable in pnet as it exists, my apologies. That resolves my concerns. You can close this issue now.

I still think it's a good idea to look at modularizing the packet parsers.

**Comment by moosingin3space** [comment]
I'm thinking a `pnet_packet` crate that simply contains the packet types and is depended upon by `pnet`. This way, we can share low-level networking parsing infrastructure between multiple projects.
