### ISSUE TITLE
Should `#[packet] struct` members be public?

### ISSUE THREAD

**Issue by zbanks** [libpnet/libpnet#256]
Is there a reason that the #[packet] structs (e.g. ``Ethernet``) are public, but none of the fields are public?

I might be misunderstanding the intended encapsulation, but it seems that the structs should either be completely private, or the members should be public. Currently, I think they can only be used as an opaque copyable packet blob -- which ``[u8]`` also does.

Example commit making them public: https://github.com/zbanks/libpnet/commit/1002b9f8c4372f00b89e9a18ca8fcdc4b45e2148

**Comment by mrmonday** [comment]
Sorry for the slow response, this got lost in my inbox.

I honestly thought they were public. I can't think of any reason for them not to be.

@faern, can you think of any reason these aren't public?

If not, we'd happily accept a pull request, particularly since you've already done the work!

**Comment by faern** [comment]
I thought you were supposed to only use the generated `*Packet` version of each struct, accessing the members with their generated getters and setters? That has been my thought all the time. Since the getters and setters will correctly translate endianness and do other magic they should be used in contrast to trying to modify fields manually.

**Comment by faern** [comment]
If my above argument is correct, then we should make those struct private instead. Maybe this was a workaround. If the struct is private maybe the generated struct is private? And we need the generated struct to be public, so maybe this was the fix?

**Comment by zbanks** [comment]
@faern it seems like the `from_packet` methods call the getters, so the endianess &c is handled. 

If the entire struct is made private, what's the point of the `FromPacket` trait?

**Comment by mrmonday** [comment]
I think the fields are meant to be public, for exactly the reason @zbanks brings up.

I believe the reason this hasn't come up yet, is because we don't have the opposite of `FromPacket` currently.

**Comment by zbanks** [comment]
The opposite of the `from_packet` method is the `populate` method on `Mutable*Packet`s, but it's not part of a trait.

**Comment by mrmonday** [comment]
So it is - I'd completely forgotten about that. Thanks for the merge request :)

**Comment by Trolldemorted** [comment]
Is there a reason that 1002b9f8c4372f00b89e9a18ca8fcdc4b45e2148 was committed to master before the bump to 0.17.0, but was excluded from the 0.17.0 release?

**Comment by mrmonday** [comment]
Looks like it was committed after the `0.17.0` release - I'll do a version bump and push out `0.17.1` this afternoon.

**Comment by mrmonday** [comment]
Done - https://crates.io/crates/pnet/0.17.1

**Comment by Trolldemorted** [comment]
should `TcpOption`'s members also be public, or get more functions?

`TcpPacket` offers a `get_options()` method, but i cannot find a way to interact (i.e. determine the type and value) with them.

**Comment by polachok** [comment]
You can use get_options_iter() which returns an iterator over  TcpOptionPacket

**Comment by mrmonday** [comment]
@Trolldemorted I believe they should be, yes.
