### ISSUE TITLE
pnet should reexport the ipnetwork crate

### ISSUE THREAD

**Issue by marmistrz** [libpnet/libpnet#274]
It's currently impossible to pattern match `pnet::datalink::NetworkInterface::ips` members without manually importing `ipnetwork`:

```
let ifaces: Vec<datalink::NetworkInterface> = datalink::interfaces();
for i in infaces {
    match i.ips {
        ipnetwork::IpNetwork::V4 => {}
        ipnetwork::IpNetwork::V6 => println!("this computer has an ipv6 addres!"),
    }
}
```

context: https://www.reddit.com/r/rust/comments/4jvxaz/reexport_dependency_pros_and_cons/

**Comment by mrmonday** [comment]
Would you mind making a pull request for this, if you have time?
