### ISSUE TITLE
Compilation without pcap

### ISSUE THREAD

**Issue by angel-manuel** [libpnet/libpnet#289]
I'm interested just in packet parsing. I would like to avoid including the pcap dependency.
I've tried to disable all features but the datalink module(i don't needed it either) fails to compile.
Is there any way?

**Comment by mrmonday** [comment]
Breaking out the packet parsing into its own crate is something we'd like to achieve, but we're not there yet. @faern has started some of that work in #288.

The pcap dependency is optional, and isn't built by default - I don't know why it's being pulled in for you. If you can provide some more information we can try and figure out what's happening for you.

**Comment by faern** [comment]
@angel-manuel That is definitely coming! I'm on the other side of the spectrum, I want to use `datalink` but without anything else. Give me a while and I will have broken out the datalink stuff at least and then maybe the rest will work better for you.
The goal is to also make the packet stuff it's own crate, but that might take a bit longer.

**Comment by angel-manuel** [comment]
After the last commits, I can avoid datalink by commenting references on lib.rs and on Cargo.toml

I would be satisfied with it being a feature. No need for packet to be on a whole different crate.
It wouldn't solve @faern problem though.

**Comment by faern** [comment]
Ah. Yeah, the `pnet_datalink` dependency should probably be a feature, true. Otherwise you can't get the packet without datalink of course! I was mostly happy I could now use datalink without packet :)

I'll put it behind a future (that is active by default).

**Comment by faern** [comment]
@angel-manuel Check if https://github.com/libpnet/libpnet/tree/add-datalink-feature satisfies your needs.

**Comment by angel-manuel** [comment]
@faern Yes, it works perfectly. Thanks a lot.

**Comment by faern** [comment]
@angel-manuel However, we are likely not going to merge that. But at some point the package module will be split out into its own crate. You can even help do that if you would like.
