### ISSUE TITLE
Support packages without fixed endianness

### ISSUE THREAD

**Issue by bkchr** [libpnet/libpnet#293]
Hi, I currently work with endianness, a library to talk to Netlink that uses libpnet. The problem is that Netlink packages does not use a fixed endianness. I created a temporary patch https://github.com/polachok/pnetlink/pull/30 that works around the problem, but as you see, this creates a lot of duplicate code. There is probably a better solution, but I think the best solution would be to fix this in libpnet. Currently if you use a type without a fixed endianness, libpnet fails at code generation with an error. 

I don't know what is the best way to solve this. I have two ideas:

1. Just support u16/u32/..
2. Add special types as for big/little endian, something like u16ne (ne = no endianness).

If we find a suitable solution for this, I would create a pull request.

**Comment by mrmonday** [comment]
I would use a `he` suffix, for "host endianness". I prefer to keep it explicit.

A pull request would be great! A ctrl-f for `"be"` in `pnet_macros_support/src/types.rs" and `pnet_macros/src/decorator.rs` should put you in the right place. I'm happy to provide any other assistance you need.
