### ISSUE TITLE
Wrong documentation link in crates.io entry

### ISSUE THREAD

**Issue by Dash83** [libpnet/libpnet#307]
Just wanted to drop you an FYI that in the link for this crate on crates.io (https://crates.io/crates/pnet), in the top level links (homepage, documentation, repository, dependant crates) the documentation link points to what I assume is an old documentation page that doesn't match up to the latest docs of the crate.
Wong link => http://octarineparrot.com/assets/libpnet/doc/pnet/
Current docs => https://docs.rs/pnet/0.20.0/pnet/

Cheers.

**Comment by mrmonday** [comment]
I don't know why crates.io points to the wrong location, I can't find any reference to the wrong/old link anywhere.

I've set up a redirect so the wrong URL redirects to docs.rs instead. Thanks for the report!
