### ISSUE TITLE
Optional serde support

### ISSUE THREAD

**Issue by vorner** [libpnet/libpnet#318]
Hello

Would it make sense to add optional/feature gated support for serde for some types? I'd use it with `MacAddr` (loading it from [config](https://crates.io/crates/config)), but there might possibly be more types that could be useful.

I'd provide the implementation, but I wanted to check first, as there might be reasons against that support.

**Comment by mrmonday** [comment]
As long as it's feature gated, I have no problem with this.

The same goes for any other popular crates.

**Comment by infosechoudini** [comment]
I believe this is finished. @vorner can you close?

**Comment by vorner** [comment]
Yes, sorry. I've probably failed to tag the original PR properly 😇.

**Comment by infosechoudini** [comment]
> Yes, sorry. I've probably failed to tag the original PR properly 😇.

Thanks!
