### ISSUE TITLE
Data Link Interfaces call on Windows panics

### ISSUE THREAD

**Issue by JuxhinDB** [libpnet/libpnet#329]
**libpnet version**: 0.21.0
**rustc version**: 1.26.0
**os**: Windows 10 Pro x64

---

On Windows, it appears that the following snippet always `panic!`(s)s:

```rust
extern crate pnet;
extern crate pnet_datalink;

fn send_tcp_packet() {
    let interfaces = pnet_datalink::interfaces();
}


fn main() {
    send_tcp_packet();
}
```

With the following:

```
C:\Users\JDB\Projects\learn-rust\syn-client>cargo run
   Compiling syn-client v0.1.0 (file:///C:/Users/JDB/Projects/learn-rust/syn-client)
    Finished dev [unoptimized + debuginfo] target(s) in 1.61 secs
     Running `target\debug\syn-client.exe`
thread 'main' panicked at 'FIXME [windows] unable to get interface list', C:\Users\JDB\.cargo\registry\src\github.com-1ecc6299db9ec823\pnet_datalink-0.21.0\src\winpcap.rs:335:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\debug\syn-client.exe` (exit code: 101)
```

After some digging it appears to be related to [this](https://github.com/libpnet/libpnet/blob/89b7f5f916f109fe8588e02eea0bfcc6fdb84b90/pnet_datalink/src/winpcap.rs#L335) line of code.

List of local Network Interfaces:

```
Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
vEthernet (DockerNAT)     Hyper-V Virtual Ethernet Adapter #3          25 Up           00-15-5D-00-02-1A        10 Gbps
vEthernet (Default Swi... Hyper-V Virtual Ethernet Adapter             23 Up           16-15-7D-77-FF-87        10 Gbps
Bluetooth Network Con...2 Bluetooth Device (Personal Area Ne...#2      20 Disconnected 00-1A-7D-DA-71-02         3 Mbps
vEthernet (nat)           Hyper-V Virtual Ethernet Adapter #2          13 Up           00-15-5D-8A-D4-25        10 Gbps
vEthernet (ArchLinux E... Hyper-V Virtual Ethernet Adapter #4          12 Up           70-85-C2-0B-7F-DC       100 Mbps
Ethernet                  Intel(R) Ethernet Connection (2) I219-V       6 Up           70-85-C2-0B-7F-DC       100 Mbps
```

I would love to submit a PR, however I am not all to proficient in Rust; especially not at such a low layer. If anyone would love to guide me through it, I would be more than happy to contribute. Otherwise it would be cool if we could push a fix for it, or at least a temporary workaround.

**Comment by Trolldemorted** [comment]
Does windows support sending arbitrary packets from the userland?

**Comment by mrmonday** [comment]
@Trolldemorted, yes, using winpcap. This is what libpnet does.

@JuxhinDB Would you mind sharing your interface list? It looks like what's happening is that there is more interface data than libpnet is currently set up to handle. I'll see if I can reproduce this tomorrow.

**Comment by JuxhinDB** [comment]
@mrmonday - Sure thing, attaching the output of `Get-NetAdapter` below:

```
Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
vEthernet (DockerNAT)     Hyper-V Virtual Ethernet Adapter #3          25 Up           00-15-5D-00-02-1A        10 Gbps
vEthernet (Default Swi... Hyper-V Virtual Ethernet Adapter             23 Up           16-15-7D-77-FF-87        10 Gbps
Bluetooth Network Con...2 Bluetooth Device (Personal Area Ne...#2      20 Disconnected 00-1A-7D-DA-71-02         3 Mbps
vEthernet (nat)           Hyper-V Virtual Ethernet Adapter #2          13 Up           00-15-5D-8A-D4-25        10 Gbps
vEthernet (ArchLinux E... Hyper-V Virtual Ethernet Adapter #4          12 Up           70-85-C2-0B-7F-DC       100 Mbps
Ethernet                  Intel(R) Ethernet Connection (2) I219-V       6 Up           70-85-C2-0B-7F-DC       100 Mbps
```

I will also attach it to the original issue for you. Should you need anything else please let me know.

**Comment by mrmonday** [comment]
Great - looks like I should be able to reproduce it by adding a bunch of hyper-v virtual adapters. I'll see if I can put a fix together in the next few hours for you :)

**Comment by JuxhinDB** [comment]
Awesome, thanks a bunch for the quick turnaround. Just out of curiosity and in order to learn something new, please do let me know when you push a fix so that I can see how you dealt with the issue. 

From what it seems, you are starting out with a fixed buffer size to pull the list of network interfaces (insufficient for my number of interfaces). Should the buffer not be big enough, you should create a new buffer with a bigger buffer size `n` number of times, to avoid getting stuck into some memory hungry loop.

**Comment by JuxhinDB** [comment]
Sure thing! I'll give it a shot tonight or early tomorrow and start from there.

**Comment by JuxhinDB** [comment]
@mrmonday - Would you like to leave this open for the time being until the crate is updated and I can confirm it works?

**Comment by antoinesauray** [comment]
The issue is still present on the master branch, with a different error message.
`Unable to get interface list despite increasing buffer size`

**Comment by mrmonday** [comment]
It would be great if we could detect if we have sufficient permissions so we can give a better error message for this.

If not, we should at least update the error to include "or program is not running as admin" or similar.

**Comment by anhhh11** [comment]
Using name from Get-NetAdapter not works:
Use name from:

> 
> 
>     // Get all interfaces
>     let interfaces = datalink::interfaces();
>     // Filter the list to find the given interface name
>     interfaces.iter().for_each(|i| println!("{}", i));
Which result:
**\Device\NPF_{<some number...>}**: flags=0
      index: 4
      ether: 00:........................
       inet: 0.0.0.0/0

**Comment by JuxhinDB** [comment]
I'm not sure what is meant by the above @anhhh11 -- going to closing this issue. If the issue persists, let me know (with steps to reproduce) and we can re-open it.

**Comment by moxian** [comment]
Hello, I've encountered this problem today, completely unexpectedly. My app was working fine, but then i rebooted, and it no longer did with `Unable to get interface list despite increasing buffer size` panic.

https://github.com/libpnet/libpnet/blob/02d691c918af08a5a3f5ab8194e668f5e32f6ea3/pnet_datalink/src/winpcap.rs#L342-L351

I tried to debug this a bit. The `winpcap::PacketGetAdapterNames` does indeed return `false` in both of these calls. However it sets `buflen` to zero after the first one (contrary to what the docs would imply), so the second does not really increase the buffer size at all.  
Setting buflen manually to a needlessly large value did not help.

(Sadly, my powershell is kinda screwed for unrelated reasons, so i can't extract `Get-NetAdapter` output for debug purposes. Here's a snippet from `route print` though:

```
===========================================================================
Interface List
 13...00 ff c9 9a 44 52 ......TAP-Windows Adapter V9
 11...40 8d 5c 73 07 6c ......Intel(R) Ethernet Connection (2) I219-V
  1...........................Software Loopback Interface 1
 12...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter
 15...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #2
===========================================================================
```
)

I tried searching for `PacketGetAdapterNames` documentation, failed (in hindsight, they are available in the source for [Winpcap developer pack](https://www.winpcap.org/devel.htm) ), then *uninstalled WinPcap, and replaced it with npcap*.

After the winpcap->npcap switch things are working perfectly fine again. So if you're reading this because you found the error message here - this might be the solution.

**Comment by ridgebacktom** [comment]
I also experienced the "Unable to get interface list" problem. The API call does work with Npcap 1.31 and Npcap SDK 1.07.

Does anyone know if this is a Windows change that causes the behavior? Can we say that Windows 10 no longer supports legacy WinPcap installations? If so, does this imply that libpnet no longer supports legacy WinPcap installations?
