### ISSUE TITLE
Win32 `sendto` always failing with 10022 | 10045

### ISSUE THREAD

**Issue by JuxhinDB** [libpnet/libpnet#334]
Version: 0.21.0
OS: Win10 x64

---

I'm currently looking to send an IP packet (tcp) on my Windows machine. I got to the point where I built the packet, obtain and interface and try to send it, however when calling [Win32 sendto](https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto) I am receiving the following error:

```
Err(Os { code: 10022, kind: InvalidInput, message: "An invalid argument was supplied." })
```

This seemed odd as all the arguments match their corresponding datatypes and seem valid:

```
Socket: 148
Buffer: 0x2c7914f42c
Buffer Len: 36
Flags: 0
Socket To Ptr: 0x2c7914f128
Socket To Len: 16
Socket To Addr: SOCKADDR { sa_family: 2, sa_data: [0, 0, 127, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0] }
Response: -1
```

I noticed that the flags are always being set to `0`, however it seems that the Win32 API requires some flags to be passed in order to be valid. I tried playing around with a few flags such as `0x1`, `0x2`, `0x00000001` inside:

https://github.com/libpnet/libpnet/blob/9365db496216b51562977bd4eafdb98c773bae95/pnet_sys/src/windows.rs#L75-L83

To:

```rust
pub unsafe fn sendto(socket: CSocket,
                     buf: Buf,
                     len: BufLen,
                     flags: libc::c_int,
                     to: *const SockAddr,
                     tolen: SockLen)
    -> CouldFail {

    println!("\n\nWin32 sendto data");
    println!("Socket: {:?}", &socket);
    println!("Buffer: {:?}", &buf);
    println!("Buffer Len: {:?}", &len);
    println!("Flags: {:?}", &flags);
    println!("Socket to: {:?}", &to);
    println!("Socket to len: {:?}", &tolen);

    ws2_32::sendto(socket, buf, len, 0x00000001, to, tolen)
}
```

Which altered the response to the following:

```
Err(Os { code: 10045, kind: Other, message: "The attempted operation is not supported for the type of object referenced." })
```

---

Unfortunately I'm not near proficient enough to debug this further. I can confirm through WireShark that no packets are being sent and changing interfaces doesn't change the error. I was hoping someone could guide be a little further.

Attached you can find the original code calling the libpnet API. I didn't directly attach to the issue to avoid clutter.

[libpnet-tcp-test.zip](https://github.com/libpnet/libpnet/files/2144482/libpnet-tcp-test.zip)

**Comment by mrmonday** [comment]
You can't send TCP packets using the transport API on Windows. Sames goes for FreeBSD and macOS.

https://docs.microsoft.com/en-us/windows/desktop/api/winsock2/nf-winsock2-socket

> `IPPROTO_TCP`: The Transmission Control Protocol (TCP). This is a possible value when the af parameter is `AF_INET` or `AF_INET6` and the type parameter is `SOCK_STREAM`.

Since this is a raw socket, the type parameter is `SOCK_RAW`. This also explains the error message - `IPPROTO_TCP` is an invalid argument when the socket type is `SOCK_RAW`.

This is mentioned in the docs for libpnet here: https://docs.rs/pnet_transport/0.21.0/pnet_transport/index.html - though it doesn't mention Windows - it probably should.

**Comment by JuxhinDB** [comment]
Great, thanks for the clarification @mrmonday. Once I get my head around things, I'll help around with better Windows support.

**Comment by JuxhinDB** [comment]
Incase this may help someone else in the future. You can find my attempt at sending a TCP packet below. It's not correct, as the byte output currently is looking something like:

```
0000   c1 67 15 b3 90 37 d2 b8 94 4b b2 76 80 1a 0f af   Ág.³.7Ò¸.K²v...¯
0010   c2 27 00 00 01 01 08 0a 2c 57 cd a5 02 a0 41 92   Â'......,WÍ¥. A.
0020   74 65 73 74                                       test
```

However once you build your TCP packet, you can try the following:

```rust
let interfaces = pnet_datalink::interfaces();
println!("{:?}", &interfaces);

let interfaces_name_match = |iface: &NetworkInterface| iface.name == "\\Device\\NPF_{F94968E8-FBA0-410D-8CD3-F205AEAD4DC9}";
let interface = interfaces
    .into_iter()
    .filter(interfaces_name_match)
    .next()
    .unwrap();

let (mut tx, _) = match pnet_datalink::channel(&interface, Default::default()) {
    Ok(Channel::Ethernet(tx, rx)) => (tx, rx),
    Ok(_) => panic!("Unknown channel type"),
    Err(e) => panic!("Error happened {}", e),
};

loop {
    println!("{:?}", tx.send_to(&tcp_header.packet(), None));    
}
```

Bare in mind that you must change the interface from `"\\Device\\NPF_{F94968E8-FBA0-410D-8CD3-F205AEAD4DC9}"` (which is my Windows Ethernet interface) to your specific Ethernet interface. This will subsequently open an Ethernet channel with the library giving you a `DataLinkSender` (https://docs.rs/pnet_datalink/0.20.0/pnet_datalink/trait.DataLinkSender.html) which you can call `send_to` to send a packet. Note that this is not super efficient as `send_to` internally clones your packet and calls `build_and_send`:

https://github.com/libpnet/libpnet/blob/9365db496216b51562977bd4eafdb98c773bae95/pnet_datalink/src/lib.rs#L189-L203

However it makes for easier prototyping.
