### ISSUE TITLE
How to send a network layer packet by using libpnet?

### ISSUE THREAD

**Issue by LEXUGE** [libpnet/libpnet#337]
I'm trying to construct IP header and TCP packet by myself.
But I can only find send datalink layer packet or transport layer packt by using libpnet.
I don't want to construct Ethernet header by myself, but I still want to construct IP header by my self.
How to achieve that?

Thank you!

**Comment by mrmonday** [comment]
Hi,

You can use `pnet_transport` for this, make sure to pass `Layer3` as the channel type - https://docs.rs/pnet_transport/0.21.0/pnet_transport/fn.transport_channel.html

Bare in mind that if you are sending TCP/UDP packets, this will only work on Linux - Windows, FreeBSD, and macOS do not allow you to use `pnet_transport` with protocols they already handle. If this is what you're trying to achieve, you will have to use `pnet_datalink` and construct the Ethernet header.

**Comment by LEXUGE** [comment]
Hi,

I knew that.
But I found that [send_to](https://docs.rs/pnet_transport/0.21.0/pnet_transport/struct.TransportSender.html#method.send_to) method requires that `Packet` trait is impled by `packet`.
But I constructed both IP header and TCP header by myself. How can I send them?

**Comment by LEXUGE** [comment]
@JuxhinDB However, as @mrmonday said, It can work on the Linux.
I tried it.

**Comment by JuxhinDB** [comment]
You are correct, I had in mind Windows and forgot to mention it in my comment.

**Comment by mrmonday** [comment]
@LEXUGE Do you mean you've constructed the bytes directly? If so, you can wrap them in a `MutableIpv4Packet::new(my_bytes).unwrap()` to use `send_to()`.

The datalink layer stuff doesn't require using the packet stuff, transport/network do though.

**Comment by LEXUGE** [comment]
@mrmonday Not that situation really.
I mean how to combine my IP header and TCP header together and impl the Packet trait?

**Comment by mrmonday** [comment]
@LEXUGE This is what @JuxhinDB's code does.

Could you give some sample code, maybe that would help?

**Comment by mrmonday** [comment]
Providing `self.packet` is a valid packet, it should be fine.

I have never tried this before.

**Comment by LEXUGE** [comment]
Finally, I solved it by using `TcpPacket`.

the code can be found in [lib_blaster](https://github.com/LEXUGE/lib_blaster)'s [build_pkt](https://github.com/LEXUGE/lib_blaster/blob/257ec5d29f89ffa6dedf522382f6c093980e0e71/src/builder.rs#L24) function. (The [sender.rs](https://github.com/LEXUGE/lib_blaster/blob/master/src/sender.rs) may help you also.)
