### ISSUE TITLE
wg-net (low-level subgroup)

### ISSUE THREAD

**Issue by stephanbuys** [libpnet/libpnet#345]
@mrmonday `libpnet` is a no-brainer to participate in this if you are interested: https://github.com/rust-lang-nursery/net-wg/issues/15

**Comment by mrmonday** [comment]
Thank you for pinging me!

I left a... [brief comment](https://github.com/rust-lang-nursery/net-wg/issues/15#issuecomment-408595008) there.

I'll close this issue now, but feel free to tag me in the other thread or open another issue.
