### ISSUE TITLE
Windows: provide NetworkInterface description in addition to name

### ISSUE THREAD

**Issue by masche842** [libpnet/libpnet#348]
Windows/winpcap has the IP_ADAPTER_INFO type and PacketGetAdapterNames function to enumerate network interfaces. While the names are not very human-readable (e.g. F48A60DC-4371-4970-B91A-88C8773E1452 and \Device\NPF_{E6BA643C-B5C1-4A7A-9A1F-900312083BBD}, respectively), IP_ADAPTER_INFO->Description is much better: Realtek PCIe GBE Family Controller #2

pnet's NetworkInterface struct only has a name field, so the description cannot be gathered along with the name. There are two options to improve user experience (e.g. when designing a GUI): a) add a description field. downside: It will only be filled on Windows and stays empty on unix machines. b) add a method to NetworkInterface that returns the description. Same downside as a), but no need to change the struct.

**Comment by mrmonday** [comment]
I think adding a description field is a good idea - I'd be willing to mentor with this if you would like to implement it.

Sorry for the lack of response.

**Comment by mattlknight** [comment]
@masche842 @mrmonday I'm going to start working on this myself as well. @mrmonday I am going to open an Issue on migrating to winapi v0.3.
