### ISSUE TITLE
MutableEthernetPacket::owned() should use capacity, not length

### ISSUE THREAD

**Issue by jtroo** [libpnet/libpnet#353]
The title and examples should be descriptive enough.

Code that doesn't work, but I think should:
```
    // initialize payload to know the length
    let mut payload: Vec<u8> = Vec::new();
    // append to payload here

    let mut ethernet_buffer : Vec<u8> = Vec::with_capacity(14 + payload.len());
    let mut ethernet_packet = MutableEthernetPacket::owned(ethernet_buffer).unwrap();
    // manipulate packet headers and payload
```

Code that works, but uses unsafe and should not be necessary:
```
    let mut ethernet_buffer : Vec<u8> = Vec::with_capacity(14 + payload.len());
    unsafe {
        let capacity = ethernet_buffer.capacity();
        ethernet_buffer.set_len(capacity);
    }
    let mut ethernet_packet = MutableEthernetPacket::owned(ethernet_buffer).unwrap();
```

Rust information:
rustc 1.27.1

Cargo information:
[dependencies.pnet]
version = "0.21.0"

[dependencies.pnet_datalink]
version = "0.21.0"

**Comment by jtroo** [comment]
I'll elaborate on the use case for this pattern. I'm using an L2 payload not supported by libpnet into and manipulating it further after `ethernet_packet` has been created, then repeatedly calling `ethernet_packet.set_payload()`.

The alternative to the code would be to initialize the full packet, including DST MAC, SRC MAC, and ETYPE, but then I'd need to initialize the payload again. In my view the 1st code example is the cleanest and easiest to understand.

**Comment by Draphar** [comment]
I think this is a Rust limitation. When allocating a `Vec`, there are no guarantees about the data stored at its memory location, so you have to first initialize it (or use unsafe code). This is why you normally use something like `vec[0; len]` to create a buffer. I have also run into this slightly confusing thing myself a couple of times, but eventually just got used to it.

**Comment by jtroo** [comment]
Ah I see, that should do it.
