### ISSUE TITLE
Migrate to winapi v0.3+

### ISSUE THREAD

**Issue by mattlknight** [libpnet/libpnet#362]
I've noticed some legacy code in libpnet that I'm working on cleaning up in my personal fork. In doing so, I'm also migrating to latest version of winapi, where I've contributed a fair amount to iphlpapi support. Any issues with me working on a PR for updating code to support latest winapi? @mrmonday  Also, I'm super new to github workflows and cross fork merges, etc.., so I do apologize in advance :D

**Comment by mrmonday** [comment]
I look forward to your PR, let me know if you need a hand with anything.

PS Sorry in advance for my inevitably delayed responses - please keep chasing me if I don't respond within a couple of days!
