### ISSUE TITLE
The packet size of Ipv4 is calculated falsely

### ISSUE THREAD

**Issue by Draphar** [libpnet/libpnet#368]
The [`ipv4_payload_length()`] function is calculating the payload length using the `total_length` field + the `header_length` field. However, the `total_length` is in bytes, while `header_length` is in 32-bit words. For instance, let's say `header_length = 5` and `total_length = 60`. You would expect `packet_size()` to return `60`. But since `header_length` is not multiplied by 4, it actually returns `75`. 

I think #109 is the same problem.

I would like to make a pull request to fix this, but unfortunately I am not familiar with the macros that generate the impls.

[`ipv4_payload_length()`]: https://github.com/libpnet/libpnet/blob/master/pnet_packet/src/ipv4.rs.in#L235

**Comment by mattlknight** [comment]
@Draphar  I can take a stab at the PR, can you provide any simple example of where the problem is occurring and what you expect (in code form)?. Or maybe jump on IRC so I can isolate where this issue is happening. I ask, becuase when I looked at the payload length function in master, I see this
```rust
fn ipv4_options_length(ipv4: &Ipv4Packet) -> usize {
    // the header_length unit is the "word"
    // - and a word is made of 4 bytes,
    // - and the header length (without the options) is 5 words long
    (ipv4.get_header_length() as usize * 4).saturating_sub(20)
}
```

So I'm thinking this section just needs to be correct with a `* 4` after as usize.
```rust

fn ipv4_payload_length(ipv4: &Ipv4Packet) -> usize {
    (ipv4.get_total_length() as usize).saturating_sub(ipv4.get_header_length() as usize)
}
```

**Comment by Draphar** [comment]
Yes, that is exactly what I meant. The `* 4` should fix it.

**Comment by mattlknight** [comment]
I'll see if I can draft up a PR for this, and potentially fix/write some test cases. @Draphar  @mrmonday

**Comment by drrlvn** [comment]
I think #308 already addresses this issue, doesn't it?
