### ISSUE TITLE
LICENSE and README.md missing from sub rust package crates

### ISSUE THREAD

**Issue by sayanchowdhury** [libpnet/libpnet#371]
The crates uploaded for
- pnet_base
- pnet_datalink
- pnet_macros
- pnet_macros_support
- pnet_packet
- pnet_sys
- pnet_transport

in crates.io don't contain the LICENSE and README.md file in the crate.

**Comment by kishiguro** [comment]
Thanks. Let me add LICENSE and README.md for each packages.

**Comment by kishiguro** [comment]
Just added LICENSE files.   README.md is referred as `readme = "../README.md"` until we have each sub package documentation.  Will be reflected in next release 0.27.0.
