### ISSUE TITLE
datalink:: NetworkInterface::mac_address will panic on virtual interfaces

### ISSUE THREAD

**Issue by nemosupremo** [libpnet/libpnet#373]
I have some code like this which will grab all the network interfaces:

```rust
for iface in datalink::interfaces() {
                    let mac = iface.mac_address()
                    
                    interfaces.push(Interface {
                        name: iface.name,
                        address: format!(
                            "{:02X}:{:02X}:{:02X}:{:02X}:{:02X}:{:02X}",
                            mac.0, mac.1, mac.2, mac.3, mac.4, mac.5
                        ),
                    });
                }
```

On a box with an openvpn connection, the above code snippet will panic when trying to read the mac_address of `tun0`.

```
tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1300
        inet 10.223.1.59  netmask 255.255.0.0  destination 10.223.1.59
        inet6 fe80::50a1:97:725d:fee9  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 768 (768.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

I'm not sure what the right thing to do here, but it seems like providing the `mac_address` function seems a little unsafe. I was a unaware this function could panic (it happened on a release build with debug symbols stripped), so it was somewhat surprising to catch. OTOH, this could just be a bug.

**Comment by JuxhinDB** [comment]
Thanks for reporting this. Apologies for the late reply from my end.

From what I can tell, I would classify this as a bug. I'll see if I can setup an openvpn box with similar interfaces to reproduce it and fix. 

If you wish, you are also more than welcome to submit a PR and we'll work on it together.

**Comment by nemosupremo** [comment]
Is it really a bug? It makes sense that a virtual interface probably won’t have a MAC address. 

The reason I reported this is that this was pretty to catch for me as the crash happened on a remote machine running a production build. It’s surprising that that function uses unwraps rather than just returning an option. I think a fix here would either to be deprecate the function or change the return type - both of which breaks the library API. I don’t know how many people use this library but that’s something that’s always preferably avoided.

**Comment by JuxhinDB** [comment]
I do get what you mean. I may figure out a way to issue a deprecation warning on the existing function and implement an new one that returns `Result` or something along those lines.

**Comment by JuxhinDB** [comment]
@nemosupremo do you have a simple setup (i.e. container) with a similar setup? This would make it much easier for me to reproduce and work on.

**Comment by alirez** [comment]
This issue seems to be reproducible using a simple tun device.

- Create a tun device:
```
sudo ip tuntap add mode tun dev dummy-tun0
```

- Then run this code:
```rust
use pnet::datalink;

fn main() {
    for iface in datalink::interfaces() {
        println!("{}", iface.mac_address());
    }
}
```

**Comment by kishiguro** [comment]
Thanks, I could reproduce the issue.
As @nemosupremo pointed out, we should avoid executing unwrap() in the library and just simply return Option<MacAddr> to the caller.  Let me make a PR for it.

**Comment by kishiguro** [comment]
Since mac field of struct NetworkInterface is pub, I would suggest that making mac_address() to be deprecated and use NetworkInterface.mac instead.

``` rust
use pnet::datalink;

fn main() {
    for iface in datalink::interfaces() {
        if let Some(mac) = iface.mac {
            println!("{}", mac);
        } else {
            println!("No mac address");
        }
    }
}
```
