### ISSUE TITLE
Trying to understand pnet::packet::Packet

### ISSUE THREAD

**Issue by Gymmasssorla** [libpnet/libpnet#378]
The [`packet()`](https://docs.rs/pnet/0.22.0/pnet/packet/trait.Packet.html#tymethod.packet) method returns whole packet data including protocol headers, and the [`payload()`](https://docs.rs/pnet/0.22.0/pnet/packet/trait.Packet.html#tymethod.payload) method returns data that a user has specified. Is it right?

**Comment by JuxhinDB** [comment]
Hi @Gymmasssorla -- that would be correct. Are you currently experiencing any issues with this?

**Comment by Gymmasssorla** [comment]
Nope, just wanted to make sure of it. Thank you for your answer!
