### ISSUE TITLE
No packets captured on local interface

### ISSUE THREAD

**Issue by dantodor** [libpnet/libpnet#381]
I'm trying to run the packetdump example on local interface to see packet capture capabilities. 
Context: macOs 10.14.5 Mojave, rustc stable 1.36
While there are no errors and no compilation issues, the output I get on lo0 is 

`[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 66

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 66

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 66

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 66

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 66

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 66

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 66

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 66

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 66

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 74

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 86

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 74

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 86

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 74

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 86

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 74

[lo0]: Unknown packet: 00:00:00:00:00:00 > 00:00:00:00:00:00; ethertype: EtherType(0) length: 86`

I am generating IPv4 traffic by a couple of apps ...
What am I doing wrong ?

**Comment by JuxhinDB** [comment]
Hey @dantodor -- thanks for raising this. Could you please provide me with a minimal code snippet that reproduces this.

**Comment by dantodor** [comment]
Hey... Sorry for late reply... There isn't too much code to show. I just ran cargo new, then pasted the contents of the packet capture example inside it...

**Comment by 06chaynes** [comment]
I'm seeing the same thing on macos loopback. tcpdump is showing IPv4 and IPv6 packets, but get_ethertype() in the handle_ethernet_frame function isn't getting a match. Still looking into why
