### ISSUE TITLE
HTTP call thought network interface

### ISSUE THREAD

**Issue by clintnetwork** [libpnet/libpnet#385]
Hi,

Is it possible to perform a http query though a network interface (i.e. eth1) ?

Thank you

**Comment by JuxhinDB** [comment]
Really isn't the scope of libpnet as it's primarily focused on low level networking (L2/3/4) rather than application layer protocols. It is recommended to instead use a dedicated package such as [http](https://docs.rs/http/0.1.18/http/). Hope this answers your question.

**Comment by clintnetwork** [comment]
Yeah sure, but it's a low-level networking because it's on a specific interface, I don't find any solution :(
