### ISSUE TITLE
Release v0.23.0

### ISSUE THREAD

**Issue by kacejot** [libpnet/libpnet#387]
Hi guys,
How soon the new release is supposed to happen?
I'm waiting for `pnet::transport::IcmpTransportChannelIterator::next_with_timeout` on stable.
Could you also give me a stable revision with this feature, so I could use it instead of master branch?

**Comment by JuxhinDB** [comment]
Hi @kacejot -- unfortunately it looks like this project isn't really being maintained any longer. I would've loved to help contribute further, however I still would need mentorship from the original authors (and time) which makes this difficult to achieve. 

If it's something you think you can help with, feel free to open an PR and I'll review it and we can merge.

**Comment by mrmonday** [comment]
@JuxhinDB I can give you access to publish to `crates.io` if you don't already have it.

Take a look at previous "bump version" PRs for what needs doing - basically just bump up version numbers in toml files and the README, then follow the normal cargo publish procedure (I try to make sure to do this in a fresh clone so that other files don't get published by accident).

**Comment by mrmonday** [comment]
Re: mentorship, I'm always happy to help if you have specific questions. I might be a little slow to respond, but I will help if I can.

**Comment by JuxhinDB** [comment]
@mrmonday feel free to provide me with access. If you need details you should be able to DM me on twitter (@juxhindb). I can then take it from there and try to handle the release. Thanks!

**Comment by mrmonday** [comment]
@JuxhinDB I've sent invites to you for (hopefully) all the `pnet*` crates on `crates.io` - let me know if I've missed any.

**Comment by JuxhinDB** [comment]
@mrmonday Seems to be all of them. Thank you :-)

**Comment by kacejot** [comment]
@JuxhinDB, so you're in charge here now :) What are your thoughts about making new release?

**Comment by JuxhinDB** [comment]
Apologies for the late reply. :-)

I'm setting a reminder to look into this later this week (ideally today) to come up with an idea on how to proceed. Hopefully we'll have this done soon enough

**Comment by JuxhinDB** [comment]
Apologies for the late reply regarding this. Opened PR - https://github.com/libpnet/libpnet/pull/390

@mrmonday let me know if anything seems off. I'll give it some time then I'll merge

**Comment by JuxhinDB** [comment]
Looks good to go. Forgot to squash commits but hopefully that isn't an issue. I'll leave the issue open to make sure that things still work for you guys

**Comment by mrmonday** [comment]
I think the only thing missing is the git tag, otherwise looks good :)

Thank you @JuxhinDB!

**Comment by JuxhinDB** [comment]
@mrmonday Drafted and released one now. I just tied it with the source code (no additional binaries). Pleasure to help

**Comment by kacejot** [comment]
@JuxhinDB, thanks a lot! 
I think we can close this one for now.
