### ISSUE TITLE
Outdated rustfmt configuration

### ISSUE THREAD

**Issue by noah04** [libpnet/libpnet#406]
The configuration in [`rustfmt.toml`](https://github.com/libpnet/libpnet/blob/master/rustfmt.toml) is somewhat outdated. Here is the current status:

```
required_version = "0.6.1"
reorder_imports = true
format_strings = false
```

1. `format_strings = false`: This is the default configuration in the current `rustfmt`[<super>1</super>] and thus not necessary. In addition, this line causes the developer to use nightly for `cargo fmt` which is not needed.

2. `required_version = "0.6.1"`: This was introduce with d44574aa6cffb11decdb198d18c42aea63bab39c and to be honest - I don't know why. If there is anything requiring this, I'm sorry. But removing it made it possible for me to run `cargo fmt` without any error.

---

If you agree with my, I'd prepare a PR containing the changes in the `rustfmt` configuration. In addition, we could re-run `cargo fmt` over the whole crate and subcrates. It worked on my machine without any errors. See https://github.com/noah04/libpnet/commit/37069548c3d207a2f99a1e83df8c7d126b940bd8 for a preview.

---

[<super>1</super>]: https://rust-lang.github.io/rustfmt/

1: https://rust-lang.github.io/rustfmt/

**Comment by JuxhinDB** [comment]
Hey @noah04, I took a look at your fork but there seems to be a number of changes. Would you like to make the `rustfmt` changes here and we'll see how it goes? If there are no major issues, I'd go ahead and merge it.

**Comment by kishiguro** [comment]
I think we just keep reorder_imports and add edition to it.
```
reorder_imports = true
edition = "2018"
```
how do you think?
