### ISSUE TITLE
pnet_packet should now depend on newer version of pnet_macros

### ISSUE THREAD

**Issue by zhaojiangbin** [libpnet/libpnet#410]
pnet_packet v0.25.0 still has this dep spec:
```
pnet_macros = { path = "../pnet_macros", version = ">=0.20" }
```

But there is an API breaking changing after v0.21.0 in commit 7a0e9b6b1815c4bfd9354466d324349a701516aa. 

I have a crate using libpnet v0.25.0. In a certain combination of deps, cargo somehow picks pnet_macros v0.21.0. That breaks the build. This following compilation error comes from a simplified reproduction:
```
error[E0015]: calls in constants are limited to constant functions, tuple structs and tuple variants
 --> one/src/main.rs:4:27
  |
4 |     const HDRLEN: usize = MutableUdpPacket::minimum_packet_size();
  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
While this might be an issue of cargo in picking the dep versions, I think that bumping the minimum version of pnet_macros for pnet_packet could workaround the issue.

I have a simplified reproduction if you are interested, please see rust-lang/cargo#7866.

**Comment by zhaojiangbin** [comment]
Turns out this issue happens because both pnet_macros and criterion depend on regex but with different version specs. Cargo can only use pnet_macros v0.21.0 which depends on the version of regex crate that satisfies both pnet_macros and criterion. In this case, Cargo does not know that pnet_macros v0.21.0 is API incompatible with pnet_packet v0.25.0.

Please see [this cargo issue comment](https://github.com/rust-lang/cargo/issues/7866#issuecomment-582495606)

To reproduce this issue:
1. Create a new crate with `cargo new foo`.
2. Put this in foo/src/main.rs:
```
use pnet::packet::udp::MutableUdpPacket;

fn main() {
    const HDRLEN: usize = MutableUdpPacket::minimum_packet_size();
    println!("{}", HDRLEN);
}
```
3. Add below dep and dev-dep specs in foo/Cargo.toml:
```
[dependencies]
pnet ="0.25.0"
[dev-dependencies]
criterion = "0.3.1"
```
4. In foo/, run `cargo build` and expect the compilation error.

Would it possible for pnet_macros to use a different version of regex?

**Comment by kishiguro** [comment]
Forth coming pnet_packet v0.26 will have dependency to pnet_macro v0.26.
