### ISSUE TITLE
unnecessary parantheses warnings

### ISSUE THREAD

**Issue by masche842** [libpnet/libpnet#415]
When building libpnet or using a local version in depending crates I get a plethora of unused_parens warnings like this:
```
warning: unnecessary parentheses around block return value
   --> ~/workspace/target/debug/build/pnet_packet-8f1b37d7e890061b/out/ethernet.rs:118:13
    |
118 |             (_self.packet[co] as u8)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses
    |
    = note: `#[warn(unused_parens)]` on by default
```
With current rust versions this is especially annoying as warnings are displayed even if the crate isn't rebuilt.
There has been some discussion around this in https://github.com/rust-lang/rust/issues/66295, but I'm not sure how to apply this to libpnet.
A simple solution is to set a module wide #![allow(unused_parens)] in modules that include code built by pnet_macros. But this is rather hackish. 
Ideas appreciated!

**Comment by mrmonday** [comment]
The emitted code already outputs various `#[allow]`s for generated code - it would make sense to do this for any other stylistic warnings that have been introduced.

If you're interested in working on this, search for `allow` in [this file](https://github.com/libpnet/libpnet/blob/450aab7fecde9ec01f8b06fc5d214b5511642540/pnet_macros/src/decorator.rs) for examples where it's already done.
