### ISSUE TITLE
Release 0.26.0

### ISSUE THREAD

**Issue by kishiguro** [libpnet/libpnet#430]
@mrmonday @mattlknight @JuxhinDB I made some changes to repository to fix warnings and bugs.  [Milestones libpnet 0.26](https://github.com/libpnet/libpnet/milestone/2) is the summary of changes.  If you guys are ok, I may go forward for releasing 0.26.0.

**Comment by mrmonday** [comment]
Had a brief look through, my only comment is re: #424 - that block is intended for the minimum supported Rust version - there's another block to test the current stable channel.

If the minimum version has increased, it should use that version - if you want to change the policy to only support the latest Rust, you could just remove that block entirely.

**Comment by kishiguro** [comment]
Thanks for the comment.  Let me try to set the minimum supported Rust version to 1.31 (first 2018 edition).  I hope that many people shifted to 2018 edition.

**Comment by kishiguro** [comment]
With several try, it seems 1.34.2 would be the minimum supported rust version for now.  time crate require >= 1.34, and 1.34.2 is the good for security patch.

**Comment by kishiguro** [comment]
I think current main branch would be a good shape to release 0.26.0.  I've briefly tried on Linux, macOS, Windows and see no major issue.  If you guys are ok, would you mind to invlite my github account `kishiguro` to crate.io's pnet package?

**Comment by JuxhinDB** [comment]
Hey @kishiguro -- I went ahead and sent you over the invites on crates.io. Please let me know if you received them. :-)

**Comment by kishiguro** [comment]
@JuxhinDB thanks!  I've got the invites.  Let me try to update carates.io package to 0.26.0.

**Comment by kishiguro** [comment]
@JuxhinDB I may need access to pnet_sys, pnet_packet, pnet_transport as well.

**Comment by JuxhinDB** [comment]
Sorry about the delay @kishiguro -- I only saw this now. Added you to those as well. :-)

**Comment by kishiguro** [comment]
@JuxhinDB np, thanks a lot!

**Comment by kishiguro** [comment]
Just released 0.26.0. Hope i don't break the package...
