### ISSUE TITLE
Release 0.27.0

### ISSUE THREAD

**Issue by kishiguro** [libpnet/libpnet#444]
Here is rough plan for next release 0.27.0.

* update crates to newer one (at least we are planning to migrate winapi to 0.3)
* add new protocol support such as NetFlow, Layer 3 IPv6.

Also we will revisit issues as much as possible.  some of the issues are filed quite a long time ago so it may not applicable to current implementation.
If you have any specific request to next release, please comment to here.

**Comment by JuxhinDB** [comment]
I believe this can be closed as we've already release 0.27.2. If there are still missing points from the above we can have a separate milestone towards that works towards that release. :-)
