### ISSUE TITLE
Not getting vlan packets

### ISSUE THREAD

**Issue by A-Helberg** [libpnet/libpnet#460]
Hi,

I'm hoping that someone can point me in the right direction.
I seem to be unable to capture vlan ethernet frames on some machines.
From the below code, on some machines it never prints "vlan".

If I uncomment the print for the ether type, I get a lot of ARP and IPv4 packets (as expected).
I can see the vlan packets when running wireshark on the machines where the below program can't.

```
fn handle_vlan(tx: &mut Box<dyn DataLinkSender + 'static>, packet: &[u8]) {
    let vlan_packet =  VlanPacket::new(packet).unwrap();
    println!("vlan");
}

fn setup_eth_socket() {
    let interface_name = env::args().nth(1).unwrap();
    let interface_names_match =
        |iface: &NetworkInterface| iface.name == interface_name;

    // Find the network interface with the provided name
    let interfaces = datalink::interfaces();
    let interface = interfaces.into_iter()
                              .filter(interface_names_match)
                              .next()
                              .unwrap();

    // Create a new channel, dealing with layer 2 packets
    let (mut tx, mut rx) = match datalink::channel(&interface, Default::default()) {
        Ok(Ethernet(tx, rx)) => (tx, rx),
        Ok(_) => panic!("Unhandled channel type"),
        Err(e) => panic!("An error occurred when creating the datalink channel: {}", e)
    };

    println!("Started listening for packets");

    loop {
        match rx.next() {
            Ok(packet) => {
                let eth_packet = EthernetPacket::new(packet).unwrap();

                if eth_packet.get_destination().is_broadcast() {
                    //print!("Broadcast packet {}", eth_packet.get_ethertype());
                    if eth_packet.get_ethertype() == Vlan {
                        handle_vlan(&mut tx, &packet[(6 + 6 + 2)..]);
                    }
                }
            },
            Err(e) => {
                // If an error occurs, we can handle it here
                panic!("An error occurred while reading: {}", e);
            }
        }
    }
}

```

**Comment by A-Helberg** [comment]
<details open>
<summary>Ethtool for a working machine:/summary>
<br>
# ethtool -k eno2
Features for eno2:
rx-checksumming: on
tx-checksumming: on
	tx-checksum-ipv4: off [fixed]
	tx-checksum-ip-generic: on
	tx-checksum-ipv6: off [fixed]
	tx-checksum-fcoe-crc: off [fixed]
	tx-checksum-sctp: off [fixed]
scatter-gather: on
	tx-scatter-gather: on
	tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: on
	tx-tcp-segmentation: on
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp-mangleid-segmentation: off
	tx-tcp6-segmentation: on
generic-segmentation-offload: on
generic-receive-offload: on
large-receive-offload: off [fixed]
rx-vlan-offload: on
tx-vlan-offload: on
ntuple-filters: off [fixed]
receive-hashing: on
highdma: on [fixed]
rx-vlan-filter: off [fixed]
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: off [fixed]
tx-gre-csum-segmentation: off [fixed]
tx-ipxip4-segmentation: off [fixed]
tx-ipxip6-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
tx-udp_tnl-csum-segmentation: off [fixed]
tx-gso-partial: off [fixed]
tx-sctp-segmentation: off [fixed]
tx-esp-segmentation: off [fixed]
tx-udp-segmentation: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off
rx-all: off
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
l2-fwd-offload: off [fixed]
hw-tc-offload: off [fixed]
esp-hw-offload: off [fixed]
esp-tx-csum-hw-offload: off [fixed]
rx-udp_tunnel-port-offload: off [fixed]
tls-hw-tx-offload: off [fixed]
tls-hw-rx-offload: off [fixed]
rx-gro-hw: off [fixed]
tls-hw-record: off [fixed]
</details>

<details open>
<summary>Ethtool for a non working one (in this case a qemu vm)</summary>
<br>
# ethtool -k ens18
Features for ens18:
rx-checksumming: on
tx-checksumming: on
	tx-checksum-ipv4: on
	tx-checksum-ip-generic: off [fixed]
	tx-checksum-ipv6: off [fixed]
	tx-checksum-fcoe-crc: off [fixed]
	tx-checksum-sctp: off [fixed]
scatter-gather: on
	tx-scatter-gather: on
	tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: on
	tx-tcp-segmentation: on
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp-mangleid-segmentation: off
	tx-tcp6-segmentation: off [fixed]
udp-fragmentation-offload: off
generic-segmentation-offload: on
generic-receive-offload: on
large-receive-offload: off [fixed]
rx-vlan-offload: off
tx-vlan-offload: on
ntuple-filters: off [fixed]
receive-hashing: off [fixed]
highdma: on [fixed]
rx-vlan-filter: off [fixed]
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: off [fixed]
tx-gre-csum-segmentation: off [fixed]
tx-ipxip4-segmentation: off [fixed]
tx-ipxip6-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
tx-udp_tnl-csum-segmentation: off [fixed]
tx-gso-partial: off [fixed]
tx-sctp-segmentation: off [fixed]
tx-esp-segmentation: off [fixed]
tx-udp-segmentation: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off [fixed]
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
l2-fwd-offload: off [fixed]
hw-tc-offload: off [fixed]
esp-hw-offload: off [fixed]
esp-tx-csum-hw-offload: off [fixed]
rx-udp_tunnel-port-offload: off [fixed]
tls-hw-tx-offload: off [fixed]
tls-hw-rx-offload: off [fixed]
rx-gro-hw: off [fixed]
tls-hw-record: off [fixed]
</details>

**Comment by Jc2k** [comment]
I remember having a similar problem with a python library and iirc vlans were getting stripped by the kernel before they hit userspace. Wireshark and tcpdump were actually reconstituting them with data from an aux data API.

Maybe there is something in here?

https://github.com/secdev/scapy/pull/2091

**Comment by A-Helberg** [comment]
Thanks @Jc2k 
It seems you are absolutely correct.

If the packet is coming in over a physical device, the vlan tag gets stripped.

It seems that packets originating internal ( eg. A VM with a nic, vlan tagged in the hypervisor) are not stripped of their headers, which is what I was using for my testing.

I managed to use the pcap library with few changes to the above code, to get the tagged vlan packets, and I’m still sending replies with pnet, for now that seems to work.

**Comment by infosechoudini** [comment]
Is this resolved? Can we close this?

**Comment by stappersg** [comment]
> Is this resolved? Can we close this?

Now highlighting @A-Helberg for it

**Comment by A-Helberg** [comment]
I'm not sure.

I was under the impression that this library should capture both incoming and outgoing packets, the same way libpcap used by wireshark does?

If I am mistaken it can be closed

**Comment by stappersg** [comment]
Summary:  **close**

The _I seem to be unable to capture vlan ethernet frames on some machines._ is explained ( _vlans were getting stripped by the kernel before they hit userspace_)

There is no needed to have this issue danling for the next time that a _triage heroine_ or _triage hero_ like @infosechoudini comes along.

@A-Helberg as creator of the issue you have _github power_ to close this issue. We, infosechoudini and I don't have (rightnow) power  to close  this issue. But we are loosing energy on this stale issue. So please close it.

**Comment by Jc2k** [comment]
Would it be a good idea to document the limitations of this library (in comparison to tcpdump/wireshark type tools which are able to "see" the vlan frames)? It's kind of surprising that you can't see the Vlan data.

**Comment by stappersg** [comment]
@A-Helberg thanks for closing

@Jc2k thanks for _vlans were getting stripped by the kernel before they hit userspace. Wireshark and tcpdump were actually reconstituting them with data from an aux data API._  Time will tell how often we have to explain that.

**Comment by infosechoudini** [comment]
Let's create a feature request for this, reassembly of VLAN and other type of headers

**Comment by stappersg** [comment]
On Sat, Apr 23, 2022 at 11:22:23AM -0700, Harry Thomas wrote:
> Let's create a feature request for this, reassembly of VLAN and other type of headers

Euh, this issue has now a link to #558 ...

**Comment by infosechoudini** [comment]
> On Sat, Apr 23, 2022 at 11:22:23AM -0700, Harry Thomas wrote: Let's create a feature request for this, reassembly of VLAN and other type of headers
> Euh, this issue has now a link to #558 ...

thanks! when we edit templates for issues, we'll put in a full feature request to track via projects
