### ISSUE TITLE
Travis not running

### ISSUE THREAD

**Issue by pheki** [libpnet/libpnet#463]
It seems to me that only appveyor is running and, as a consequence, only windows is being tested.

Also the rustc versions tested in `.travis.yml` and `appveyor.yml` differ...

**Comment by kishiguro** [comment]
thanks for reporting, let me check.

**Comment by kishiguro** [comment]
@mrmonday @JuxhinDB @mattlknight can we double check TravisCI set up?  seems it is not running...

**Comment by mrmonday** [comment]
Don't know why it wasn't triggered - I closed and re-opened all recent PRs where Travis wasn't triggered, it seems to be running now.

**Comment by kishiguro** [comment]
@mrmonday thanks a lot!
