### ISSUE TITLE
The memory layout of bpf_hdr must be repr(C).

### ISSUE THREAD

**Issue by lenna-kun** [libpnet/libpnet#465]
`struct bpf_hdr` in `pnet_datalink/src/bindings/bpf.rs` needs `#[repr(C)]` because it is used to interpret bpf packet by mem::transmute().

**Comment by kishiguro** [comment]
thanks for reporting.  Yes as you pointed out `#[repr(C)]` should be defined.  Let me fix it.

**Comment by kishiguro** [comment]
merged, let me close the ticket.
