### ISSUE TITLE
Extended LinkType Support - USB PCAP

### ISSUE THREAD

**Issue by TurnOfACard** [libpnet/libpnet#471]
I've written code for libpnet for two different [link types](https://www.tcpdump.org/linktypes.html). The one I see as more common  is the [USB PCAP link type](https://desowin.org/usbpcap/captureformat.html), I'd like to contribute the code by raising a pull request if this would be desirable?

Is there a policy for which link types are suitable for merging?

**Comment by stappersg** [comment]
Perhaps means the silence  _patches welcome_.
