### ISSUE TITLE
MinGW support?

### ISSUE THREAD

**Issue by piegamesde** [libpnet/libpnet#479]
I'm trying to compile my application on Windows using MinGW, I then ran into the `cannot find -lPacket` linker error, which led me to the `pnet` dependency after some debugging.

One of the requirements in the README states: "You must use a version of Rust which uses the MSVC toolchain". Does this imply that there is no MinGW support?

**Comment by mrmonday** [comment]
If you have a mingw compiled version of the winpcap or npcap packet library, it should be possible to make this work.

Last time I touched this, there was no pre-compiled binary, so this was never tested/made to work.

If you manage to make it work, we'd really appreciate a pull request updating the documentation.

**Comment by piegamesde** [comment]
I figured out that I only depended on `pnet` for some small feature, and that there are smaller crates that provide exactly that feature without the rest, and it seems to work on Windows so far.

As I'm not really much into Windows development and I found a solution for my specific problem, I don't have the resources to investigate this further.
