### ISSUE TITLE
Packetdump example not working on windows

### ISSUE THREAD

**Issue by abusalaa7** [libpnet/libpnet#481]
I was able to run the [packet dump example](https://github.com/libpnet/libpnet/blob/master/examples/packetdump.rs) on macos and on ubuntu but on windows it doesn't seem to capture any packets. The program is running but it's not printing any output and not throwing any errors or exiting.

I followed the instructions and installed winpcap 4.1.3 and copied the dll to this directory
\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib

I also tried uninstalling winpcap, installing npcap with the api compatibility mode. I left the dll in the lib folder.

The program compiles and my printlln prints that it enters the loop only once. It seems like the rx is waiting forever without receiving any packets and never re-enters the loop.

Any help is appreciated.

Rust version: rustc 1.51.0 (2fd73fabe 2021-03-23)
Windows: 10 version 1803

**Comment by StanislavGlebik** [comment]
Run into the same issue with arp example

**Comment by ridgebacktom** [comment]
examples/packetdump.rs seems to have code that is not for macos or ios only:
https://github.com/libpnet/libpnet/blob/2ad90983ddc10e985392872c6ffd1e3fef7ce2d5/examples/packetdump.rs#L252

Was the above intentional? Are the examples meant to be cross-platform?

**Comment by abusalaa7** [comment]
I tried commenting that part and it still won't work.

**Comment by ridgebacktom** [comment]
On Windows, using nightly, it seems like the offset() function is not correctly setting the end pointer:
https://github.com/libpnet/libpnet/blob/2ad90983ddc10e985392872c6ffd1e3fef7ce2d5/pnet_datalink/src/winpcap.rs#L246

Inserting a debug, I see that **buflen** is continually changing, reflecting the capture of frames, but when **ptr** and **end** are set, the **end** pointer is always the same as the **ptr** variable.
https://github.com/libpnet/libpnet/blob/2ad90983ddc10e985392872c6ffd1e3fef7ce2d5/pnet_datalink/src/winpcap.rs#L241

The offset() function seems to be an experimental function on the rustc nightly toolchain.
https://doc.rust-lang.org/std/intrinsics/fn.offset.html

I did some experiments, and it seems that neither add() nor offset() (pointer functions, see https://doc.rust-lang.org/std/primitive.pointer.html#method.add) are working the way I expect. For example, the following code prints the same value for both pointers:

```
unsafe {
  println!("PTR: {:?} END: {:?}", ptr, ptr.add(0x8888));
}
```

The pointer arithmetic seems unique to the winpcap.rs code. I may be misunderstanding how Rust handles pointer arithmetic, but it almost seems like something is not working as expected in the rust compiler. (1.53.0-nightly)

**Comment by ridgebacktom** [comment]
To make the packet capture work correctly on Windows, add these lines to the Cargo.toml file:

```
[target.'cfg(windows)'.dependencies]
# winapi = "0.3.8" # This will not work because the size of c_void defaults to 0.
winapi = { version = "0.3.8", features = [ "std" ] }
```

The root problem is that using the winapi dependency without the "std" feature means that the default size of the buffer elements (referenced by a c_void pointer) is 0, which makes the pointer arithmetic return incorrect values. Including the std feature makes the c_void pointer arithmetic work as expected.

Many thanks to @mbrubeck for pointing out the problem over at the Rust forums. (https://users.rust-lang.org/t/pointer-arithmetic-on-windows/59512/7)

After modifying the Cargo.toml file, packet capture works as expected.

**Comment by abusalaa7** [comment]
It worked. Thank you so much for your help.

**Comment by abusalaa7** [comment]
@stappersg - is there a contributions guide?

**Comment by stappersg** [comment]
On Mon, May 10, 2021 at 04:39:00PM -0700, Ahmed Mansour wrote:
> @stappersg - is there a contributions guide?

Just "be a good contributor". My merge request was accepted
without any "you MUST first agree with ..."  :-)

So begin


Do know that the libpnet README.md has
  Discussion and support: #libpnet on freenode


Feel welcome

**Comment by stappersg** [comment]
@abusalaa7  how is the progress on providing a patch for this issue?

**Comment by stappersg** [comment]
In #501 is / was announced that _freenode_ has been replaced by _libera_.
