### ISSUE TITLE
How to get getway value

### ISSUE THREAD

**Issue by patrickelectric** [libpnet/libpnet#482]
Is it possible to get it ? Where it could be implemented if not ?

**Comment by infosechoudini** [comment]
I'm not sure I understand, can you elaborate?

**Comment by stappersg** [comment]
> can you elaborate

@patrickelectric just closing this issue is also much better as letting it rot  (as it did the first year since creation).

**Comment by patrickelectric** [comment]
I'll close it for now, if somehow my mental brain reloads such information again I'll reopen and update the description, thanks!
