### ISSUE TITLE
Build error with pnet_macros v0.28.0 and pnet_macros v0.23.1

### ISSUE THREAD

**Issue by laumann** [libpnet/libpnet#499]
Hi! Thanks for a great crate! I was looking at a build error this morning, and realised that we're using this crate in many parts of our dependency tree - so it must be good :-)

The error looks as follows:
```
   Compiling pnet_packet v0.23.1
error[E0425]: cannot find function `register` in crate `pnet_macros`
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pnet_packet-0.23.1/build.rs:27:30
   |
27 |                 pnet_macros::register(&mut registry);
   |                              ^^^^^^^^ not found in `pnet_macros`
```
_Somewhere_ in our dependency tree (as rather big), we have a packet that uses pnet_packet v0.23.1 that in its build.rs has the above line. It appears that the `register()` method has been removed in the latest release.

I pinned pnet_macros to v0.26.0 and then my build completes successfully.

I imagine the preferred solution to this is to update all dependencies that uses pnet_packet v0.23.1 (seems like latest version is also v0.28.0), but I was wondering if there is a chance to have `register()` re-introduced?

**Comment by stappersg** [comment]
> wondering if there is a chance to have register() re-introduced?

Increase that chance by providing a merge request ...

**Comment by laumann** [comment]
> > wondering if there is a chance to have register() re-introduced?
> 
> Increase that chance by providing a merge request ...

I'm happy to provide some code, but I wanted to know if the removal of `register()` was intentional and if it would make sense to re-introduce.

**Comment by mrmonday** [comment]
The removal was intentional, as of `v0.28.0` we no longer use `syntex`, and instead use procedural macros.

I advise you either stick to `v0.27.2`, or upgrade everything to `v0.28.0`.

There's documentation for the new way to handle packets here: https://github.com/libpnet/libpnet/blob/141081669d577787460d865dd1110229927148da/docs/using_packet.md

**Comment by laumann** [comment]
@mrmonday Great! Thanks for the answer and the link.
