### ISSUE TITLE
Version published as `0.25.0` seems to not match git tag `0.25.0`

### ISSUE THREAD

**Issue by mkpankov** [libpnet/libpnet#524]
I've been trying to compile https://github.com/jabedude/ja3-rs

I've hit this error:
```
   Compiling pnet_packet v0.25.0
error[E0425]: cannot find function `register` in crate `pnet_macros`
  --> /home/mkpankov/.cargo/registry/src/github.com-1ecc6299db9ec823/pnet_packet-0.25.0/build.rs:27:30
   |
27 |                 pnet_macros::register(&mut registry);
   |                              ^^^^^^^^ not found in `pnet_macros`

```

However, when I downloaded this repository locally, checked it out to `0.25.0` tag, set the following override in `ja3-rs` `Cargo.toml` :
```
[patch.crates-io]
pnet = { path = "/home/mkpankov/work/libpnet/" }
```
and removed existing `Cargo.lock`, it compiled successfully:
```
   Compiling pnet v0.25.0 (/home/mkpankov/work/libpnet)
warning: `pnet_datalink` (lib) generated 7 warnings
   Compiling ja3 v0.5.0 (/home/mkpankov/work/ja3-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 5.88s
```

Is it because published version somehow different or there's another reason I'm missing?

**Comment by mrmonday** [comment]
Older versions of libpnet are not supported - please upgrade to the latest to resolve this issue.
