### ISSUE TITLE
Is is_up() working correctly? Linux

### ISSUE THREAD

**Issue by jcdc404** [libpnet/libpnet#538]
I have several interfaces on my machine. Many are internal and show "state DOWN" using the ip addr command. However, if I test against is_up() all of the interfaces return in the affirmative. The code below prints out all of the interfaces, not just those showing "state UP".

```
let ifaces = pnet::datalink::linux::interfaces();

for inf in ifaces{
    if inf.is_up(){
        println!("{}",inf);
    }
}
```

**Comment by fennewald** [comment]
`UP` can mean several things with linux network interfaces. From my machine:
```
wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
                            1^^                                 2^^^^^^^^
```
libpnet is referring to the up status denoted by the first mark, while you're referring to the second mark.

**Comment by jcdc404** [comment]
Does the library have a way to check for the state UP?

**Comment by fennewald** [comment]
Currently no. You are referring to carrier state. It can be queried through the sysfs. I am adding a patch that should add support in the forms of `is_lower_up()` and `is_dormant()`

**Comment by fennewald** [comment]
@jcdc404. it works now! `.is_lower_up()` will tell you what you were looking for before.

**Comment by zszep** [comment]
Can't find the is_lower_up in v.0.33.0

**Comment by zszep** [comment]
Ok, Looking up th source code found the directive #[cfg(any(target_os = "linux", target_os = "android"))].
So, it's working only on linux and android. Is there some other way I can find out the status of the interface on Windows.
