### ISSUE TITLE
Issue getting IPs for interfaces on OSX

### ISSUE THREAD

**Issue by lukeasrodgers** [libpnet/libpnet#55]
I'm having an issue getting IP addresses for interfaces on OSX using `get_network_interfaces`.

The problem appears to be this code: https://github.com/libpnet/libpnet/blob/ea45c1d8b7d91b98ebe4b873d2f77fcd71c632dd/src/util.rs#L226-236.

If `old.ips` is `None`, (i.e. the first interface we found for a given name has no IPs), then the new ones will never be merged in. 

I know you're working on a rewrite, so I didn't bother opening a PR, but would be happy to do so (with an attempt at a test demoing the issue) if you'd like.

**Comment by mrmonday** [comment]
I won't be touching that piece of code - I'd love a pull request if you have the time and motivation :)

**Comment by lukeasrodgers** [comment]
I'll see what I can do, cheers.

**Comment by mrmonday** [comment]
Closed by pull #75.
