### ISSUE TITLE
pnet-0.31 missing datalink module

### ISSUE THREAD

**Issue by daviessm** [libpnet/libpnet#572]
After updating my dependency from pnet-0.30 to pnet-0.31 I can no longer see the `datalink` module:

```
error[E0433]: failed to resolve: could not find `datalink` in `pnet`
   --> src\packets\capture.rs:348:34
    |
348 |         let device_infos = pnet::datalink::interfaces();
    |                                  ^^^^^^^^ could not find `datalink` in `pnet`

```

There's also no mention of the `datalink` module on docs.rs, just `packets` and `util`.

**Comment by Camille019** [comment]
On my side I need to set `std` feature to enable `datalink` and `transport` modules.

**Comment by daviessm** [comment]
Yep, looks like that works. >pnet-0.30 doesn't have the `std` feature as default.
