### ISSUE TITLE
`std` features not included by default

### ISSUE THREAD

**Issue by sebastianrex** [libpnet/libpnet#574]
It looks like the 0.30 release changed the default features, which is reasonable.

However, looking at https://github.com/libpnet/libpnet/blob/master/Cargo.toml#L22-L23, my reading is that the desire was to include `std` by default, since `default` includes the defaults from all the sub-crates, and those all include `std` by default.

However, the base `std` feature isn't included by default, which means that `ipnetwork` isn't included by default either.

This surprised me, as I had to add:

```toml
pnet = { version = "0.31", features = ["default", "std"]}
```
to my Cargo.toml to get the `std` feature enabled, in order to use `ipnetwork` via `pnet`.

I haven't submitted a PR because I wasn't sure if this was intentional or not, but it looked accidental.

**Comment by arctic-alpaca** [comment]
This also greatly reduces the documented code on [docs.rs](https://docs.rs/pnet/latest/pnet/index.html).

**Comment by mrmonday** [comment]
This should be fixed from `v0.32.0`.
