### ISSUE TITLE
Struct packet_mreq requires repr(C) in rustc versions >= 1.67

### ISSUE THREAD

**Issue by jahofmann** [libpnet/libpnet#600]
With recent rustc versions the memory layout of `packet_mreq` [pnet_datalink/src/bindings/linux.rs:32](https://github.com/libpnet/libpnet/blob/84d6cb6822e9b90232cdd36c8189827c36b0344c/pnet_datalink/src/bindings/linux.rs#L32) has changed.

Rustc 1.67.0 is the first failing version for me and the problem could be related to https://github.com/rust-lang/rust/pull/102750/.

This leads to an error in [pnet_datalink/src/linux.rs:124](https://github.com/libpnet/libpnet/blob/84d6cb6822e9b90232cdd36c8189827c36b0344c/pnet_datalink/src/linux.rs#L131) as `setsockopt` receives the differently aligned struct and fails with "os error 19". In my case the IOCTL received 0 as the (invalid) device index.

Adding `#[repr(C)]` fixes the issue.
```rust
// man 7 packet
#[repr(C)]
pub struct packet_mreq {
    pub mr_ifindex: libc::c_int,
    pub mr_type: libc::c_ushort,
    pub mr_alen: libc::c_ushort,
    pub mr_address: [libc::c_uchar; 8],
}
```

**Comment by mrmonday** [comment]
This should be fixed in v0.32.0.
