### ISSUE TITLE
[Question] what is the correct way to change source/destination IP address for TCP/UDP packets?

### ISSUE THREAD

**Issue by rohrit** [libpnet/libpnet#615]
Hi,

I am trying to change the source IP of ICMP/TCP/UDP packets on egress and destination IP on ingress from a program that is using libpnet.

The code I have works for ICMP packets and not for TCP/UDP packets.

Snippet of code attached here

```rust
// decode packet and replace src ip
let mut ipv4 = MutableIpv4Packet::new(&mut data).unwrap();
let srcip = "192.168.1.10".parse::<Ipv4Addr>().unwrap();
ipv4.set_source(srcip);

match ipv4.get_next_level_protocol() {
    IpNextHeaderProtocols::Tcp => {
        let destip = ipv4.get_destination();
        let mut tcp = MutableTcpPacket::owned(ipv4.payload().to_owned()).unwrap();
        tcp.set_checksum(tcp::ipv4_checksum(&tcp.to_immutable(), &srcip, &destip));
        ipv4.set_payload(tcp.payload());
    }
    IpNextHeaderProtocols::Udp => {
        let destip = ipv4.get_destination();
        let mut udp = MutableUdpPacket::owned(ipv4.payload().to_owned()).unwrap();
        udp.set_checksum(udp::ipv4_checksum(&udp.to_immutable(), &srcip, &destip));
        ipv4.set_payload(udp.payload());
    },
    IpNextHeaderProtocols::Icmp => (),
    _ => {
        debug!("Unknown packet type!");
        continue
    },
}

let mut out_data: Vec<u8> = vec![0; data_len];        
ipv4.set_checksum(checksum(&ipv4.to_immutable()));
out_data.clone_from_slice(ipv4.packet_mut());
```

I am writing the packet to a tun interface and the packet is forwarded out from the ethernet interface. From tcpdump, I see the packet being sent out but there is no response received. 

I am new to this library so not sure if I am using it correctly. Any help would be greatly appreciated!

**Comment by rohrit** [comment]
I figured out that I was setting the payload incorrectly in the ipv4 packet. should have set the tcp/udp packet contents instead. 

```rust
ipv4.set_payload(tcp.packet());
```

**Comment by StellarGlyph** [comment]
How do you block the original packet? Does this mean that two identical packets are sent?
