### ISSUE TITLE
RARP Example

### ISSUE THREAD

**Issue by zszep** [libpnet/libpnet#617]
Is there any way to send a RARP packet with libpnet to get an IP address having a remote MAC address. What I am trying to do:
Given a known source IP address, a known source MAC address, a known destination MAC address, I need to get the remote's IP. I have seen the ARP example, but I need the opposite.

**Comment by stappersg** [comment]
I think there is no such thing.
Yes, I could be wrong about that.
And I have no problem if someone proves wrong on it.

@zszep I don't know which challenge you are facing, but I recommend to reconsider what you call "RARP" as solution to the "problem".   Still please do share your thoughts.

**Comment by zszep** [comment]
@stappersg What I really need is to get the IP address of a computer in a LAN of which I only know the mac address and nothing else.

**Comment by stappersg** [comment]
Three months later: _Those who can close this issue, please do._

**Comment by stappersg** [comment]
Another five months later is this issue still open. Most likely I will stumble again over it. To prevent that, a less friendly approach as previously.

This _"made up RARP" issue_ is not about [RARP](https://en.wikipedia.org/wiki/Reverse_Address_Resolution_Protocol), but is _"You must tell me how I can send a packet to a layer two address that makes the remote end reply with layer three address information!"_.

Note to my future self: _Dreaming is good, making a dream come true is better._

Note to my self: _Let go, let go_
