### ISSUE TITLE
Thinking of contributing - is project still active?

### ISSUE THREAD

**Issue by victor-wei126** [libpnet/libpnet#632]
I'd like to possibly contribute - is this project still active?

**Comment by stappersg** [comment]
![image](https://github.com/libpnet/libpnet/assets/35434094/dc229fe2-a455-47d1-a7fb-8644d8cc04c9)
 
![image](https://github.com/libpnet/libpnet/assets/35434094/e1d519d3-f77e-4116-b7ac-3585f15b3c4c)

In words:  _Start contributing_

**Comment by stappersg** [comment]
The _Start contributing_ was better expressed at another project: [_Yep. Send over your patches._](https://github.com/smoltcp-rs/smoltcp/issues/818#issuecomment-1642836132)
