### ISSUE TITLE
Unable to implement tcp handshake via libpnet

### ISSUE THREAD

**Issue by rikonaka** [libpnet/libpnet#637]
I'm going to implement the tcp 3-step handshake myself, but I've noticed that after I send the first SYN packet and the targets returns an ACK packet, an RST packet automatically appears after that.

![1](https://github.com/libpnet/libpnet/assets/13602602/869f9d5c-1f11-4628-8775-641e853a8717)

I tried to locate the problem, and finally found that occur when the first SYN packet is sent.

https://github.com/rikonaka/pistol-rs/blob/ffce92379cfcdf0a9f3c4b90830d41b49f03b2b9/src/scan/tcp.rs#L616

I'm guessing that the packet was sent from the OS, as we do with ACK scans, but in this case libpnet should have taken over the port, but it doesn't seem to have.

Is there any solution to this?

Thanks!

**Comment by mkeeter** [comment]
I've run into similar issues, and found that opening an unused dummy socket will prevent the OS from automatically replying:

```rust
    // Open a bogus socket to listen on port 2000, which prevents the OS from
    // replying with ICMPv6 messages about the port being unreachable.
    let _socket = std::net::UdpSocket::bind(format!("[::]:{SOURCE_PORT}"))?;
```

This is for IPv6 + UDP, but you might be able to do something similar for IPv4 + TCP.

**Comment by rikonaka** [comment]
> I've run into similar issues, and found that opening an unused dummy socket will prevent the OS from automatically replying:
> 
> ```rust
>     // Open a bogus socket to listen on port 2000, which prevents the OS from
>     // replying with ICMPv6 messages about the port being unreachable.
>     let _socket = std::net::UdpSocket::bind(format!("[::]:{SOURCE_PORT}"))?;
> ```
> 
> This is for IPv6 + UDP, but you might be able to do something similar for IPv4 + TCP.

Thank you very much for your reply 😜, I haven't tested it yet, but I have a stupid question, will this socket conflict with libpnet?

**Comment by mkeeter** [comment]
In my testing, it didn't interfere.  I was using `pnet::datalink::channel` to build a `(tx, rx)` pair, which gives you **every packet** on the interface; then, you have to deconstruct + filter them manually.  For my code, it looked like this:
```rust
        let start = Instant::now();
        while Instant::now() - start < timeout {
            let Ok(rx) = self.receiver.next() else { continue; };
            let packet = EthernetPacket::new(rx).unwrap();
            if EtherTypes::Ipv6 == packet.get_ethertype() {
                let header = Ipv6Packet::new(packet.payload()).unwrap();
                if IpNextHeaderProtocols::Udp == header.get_next_header() {
                    let udp = UdpPacket::new(header.payload()).unwrap();
                    if udp.get_destination() == SOURCE_PORT {
                        return Some(udp.payload().to_owned());
                    }
                }
            }
        }
```

**Comment by rikonaka** [comment]
> In my testing, it didn't interfere. I was using `pnet::datalink::channel` to build a `(tx, rx)` pair, which gives you **every packet** on the interface; then, you have to deconstruct + filter them manually. For my code, it looked like this:
> 
> ```rust
>         let start = Instant::now();
>         while Instant::now() - start < timeout {
>             let Ok(rx) = self.receiver.next() else { continue; };
>             let packet = EthernetPacket::new(rx).unwrap();
>             if EtherTypes::Ipv6 == packet.get_ethertype() {
>                 let header = Ipv6Packet::new(packet.payload()).unwrap();
>                 if IpNextHeaderProtocols::Udp == header.get_next_header() {
>                     let udp = UdpPacket::new(header.payload()).unwrap();
>                     if udp.get_destination() == SOURCE_PORT {
>                         return Some(udp.payload().to_owned());
>                     }
>                 }
>             }
>         }
> ```

Thank you very much for your patience in replying, it seems that this is an unfixable bug that can only be remedied with a few tricks. 🤪
