### ISSUE TITLE
Crashed in `bpf.rs:416:44`

### ISSUE THREAD

**Issue by xmh0511** [libpnet/libpnet#645]
> thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0x7f7f5900b00e'
> 
> /.cargo/registry/src/index.crates.io-6f17d22bba15001f/pnet_datalink-0.34.0/src/bpf.rs:416:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
zsh: abort      sudo cargo run

**Comment by frankplow** [comment]
Possible duplicate of #641. Are you also using MacOS?

**Comment by xmh0511** [comment]
> Are you also using MacOS?

Yes.
