### ISSUE TITLE
Passing libpnet `Packet` struct between functions is difficult

### ISSUE THREAD

**Issue by rikonaka** [libpnet/libpnet#657]
I've tried passing a `TcpPacket` between different functions, but this seems to be an impossible operation.

```rust
fn gen_tcp_packet(ipv4_buff: &Vec<u8>) -> Option<TcpPacket> {
    let ipv4_packet = Ipv4Packet::new(&ipv4_buff);
    match ipv4_packet {
        Some(ipv4_packet) => {
            TcpPacket::new(&ipv4_packet.payload())
        }
        None => None,
    }
}
```

And the compiler say:

```
cannot return value referencing local variable `ipv4_packet` returns a value referencing data owned by the current function
```

I think the cause of this problem is that the `Packet` structure does not set `#[derive(Clone)]`, `TcpPacket` struct doesn't even have a `clone()` function, I tried to locate the relevant code in libpnet, and I found that I couldn't do it. 

So how can I pass `Packet` structure between different functions?

**Comment by Martichou** [comment]
You may need to change the structure of your code. I'm not sure adding Clone to the Packet would be a good idea for performance.. if you're handling a lot of packets, this would crash the `pkt/s` being handled.

Look at this: https://github.com/libpnet/libpnet/blob/main/pnet_macros/src/lib.rs#L48 to see if more information can help you.

**Comment by rikonaka** [comment]
> You may need to change the structure of your code. I'm not sure adding Clone to the Packet would be a good idea for performance.. if you're handling a lot of packets, this would crash the `pkt/s` being handled.
> 
> Look at this: https://github.com/libpnet/libpnet/blob/main/pnet_macros/src/lib.rs#L48 to see if more information can help you.

Thanks for your reply, I tried the method you provided but I still can't seem to return the TcpPacket structure.

```rust
fn gen_tcp_packet<'p>(ipv4_buff: &'p [u8]) -> Option<TcpPacket<'p>> {
    let ipv4_packet = Ipv4Packet::new(&ipv4_buff);
    match ipv4_packet {
        Some(ipv4_packet) => TcpPacket::new(&ipv4_packet.payload()),
        None => None,
    }
}
```

![test](https://github.com/libpnet/libpnet/assets/13602602/8854bd7d-e499-4e96-8ce9-a7661c5e7da5)

It seems as if the problem is insurmountable 😂. It looks like I have to write the code for parsing tcp packets again within each function.

**Comment by Martichou** [comment]
I guess so. With your code architecture it's not really possible atm, that's because UdpPacket doesn't own the data it uses.
Which is better for performance (avoid Clone or Copy which are expensive). What you can do is in your handling, generate the ipv4 packet from outside the gen_tcp_packet, then you can do what you want.

```
fn gen_udp_packet(ipv4_payload: &[u8]) -> Option<UdpPacket> {
    let udp = UdpPacket::new(&ipv4_payload).unwrap();
    
    Some(udp)
}

**Comment by rikonaka** [comment]
> I guess so. With your code architecture it's not really possible atm, that's because UdpPacket doesn't own the data it uses. Which is better for performance (avoid Clone or Copy which are expensive). What you can do is in your handling, generate the ipv4 packet from outside the gen_tcp_packet, then you can do what you want.
> 
> ```rust
> fn gen_udp_packet(ipv4_payload: &[u8]) -> Option<UdpPacket> {
>     let udp = UdpPacket::new(&ipv4_payload).unwrap();
>     
>     Some(udp)
> }
> ```

Thank you so much for your reply, I know what to do. 😊

**Comment by lilydjwg** [comment]
I have a similar problem, but I can't `generate the ipv4 packet from outside` because I can't generate all the layers outside as I'm writing a function parsing out the tcp packet out of bytes.

```rust
pub fn tcp_from_packet<'a>(packet: &'a [u8], linktype: Linktype) -> TcpPacket<'a> {
  match linktype {
    Linktype::ETHERNET => {
      let ether = EthernetPacket::new(packet).unwrap();
      ether_to_tcp(ether.payload(), ether.get_ethertype())
    }
    Linktype::LINUX_SLL2 => {
      let sll2 = SLL2Packet::new(packet).unwrap();
      ether_to_tcp(sll2.payload(), sll2.get_protocol_type())
    }
    _ => {
      panic!("unsupported datalink type: {:?}", linktype);
    }

  }
}

fn ether_to_tcp<'a>(packet: &'a [u8], ethertype: EtherType) -> TcpPacket<'a> {
  match ethertype {
    EtherTypes::Ipv4 => {
      let ip = Ipv4Packet::new(packet).unwrap();
      TcpPacket::new(ip.payload()).unwrap()
    },
    EtherTypes::Ipv6 => {
      let ip = Ipv6Packet::new(packet).unwrap();
      TcpPacket::new(ip.payload()).unwrap()
    },
    ty => {
      panic!("not ipv4 or ipv6 packet: {}", ty);
    }
  }
}
```
