### ISSUE TITLE
How to send icmp packets?

### ISSUE THREAD

**Issue by cppcoffee** [libpnet/libpnet#665]
Hi, I constructed an icmp packet of type `DestinationUnreachable` and sent it, actually using `tcpdump -i any icmp -w /tmp/1.pcap` did not catch any icmp packets sent?

I searched the repository source code, but I couldn't find an example of icmp sending, may I ask how to send `DestinationUnreachable` icmp packets correctly?

Found out that the `icmp::checksum` function doesn't accept the `DestinationUnreachablePacket` type.

The demo as follows:

```rust
use std::net::{IpAddr, Ipv4Addr};

use anyhow::{anyhow, Result};
use pnet::packet::icmp::destination_unreachable::{IcmpCodes, MutableDestinationUnreachablePacket};
use pnet::packet::icmp::IcmpTypes;
use pnet::packet::ip::IpNextHeaderProtocols;
use pnet::transport::{transport_channel, TransportChannelType};

fn main() -> Result<()> {
    let dst_ip = IpAddr::V4(Ipv4Addr::new(1, 1, 1, 1));

    let (mut icmp, _) =
        transport_channel(0, TransportChannelType::Layer3(IpNextHeaderProtocols::Icmp))?;

    let mut data = vec![0u8; 64];
    let mut pkg = MutableDestinationUnreachablePacket::new(&mut data).ok_or(anyhow!(
        "Failed to create ICMP Destination Unreachable packet"
    ))?;

    pkg.set_icmp_type(IcmpTypes::DestinationUnreachable);
    pkg.set_icmp_code(IcmpCodes::DestinationProtocolUnreachable);
    pkg.set_payload(&[]);

    // ERROR: The icmp::checksum function doesn't accept the DestinationUnreachablePacket type.
    //pkg.set_checksum(icmp::checksum(&pkg.to_immutable()));

    icmp.send_to(&pkg, dst_ip)?;

    Ok(())
}
```

**Comment by zszep** [comment]
Here is the way I do it:

`use pnet::packet::{
    icmp::{
        echo_reply::EchoReplyPacket,
        echo_request::{IcmpCodes, MutableEchoRequestPacket},
        IcmpTypes,
    },
    ip::IpNextHeaderProtocols,
    util, Packet,
};
use pnet_transport::icmp_packet_iter;
use pnet_transport::TransportChannelType::Layer4;
use pnet_transport::{transport_channel, TransportProtocol};
use rand::random;
use std::{
    env,
    net::IpAddr,
    sync::{Arc, RwLock},
    time::{Duration, Instant},
};

const ICMP_SIZE: usize = 64;

fn main() -> anyhow::Result<()> {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        panic!("Usage: icmp-demo target_ip");
    }
    let target_ip: IpAddr = args[1].parse().unwrap();
    println!("icpm echo request to target ip:{:#?}", target_ip);

    let protocol = Layer4(TransportProtocol::Ipv4(IpNextHeaderProtocols::Icmp));
    let (mut tx, mut rx) = match transport_channel(4096, protocol) {
        Ok((tx, rx)) => (tx, rx),
        Err(e) => return Err(e.into()),
    };

    let mut iter = icmp_packet_iter(&mut rx);
    loop {
        let mut icmp_header: [u8; ICMP_SIZE] = [0; ICMP_SIZE];
        let icmp_packet = create_icmp_packet(&mut icmp_header);
        let identifier = icmp_packet.get_identifier();
        let timer = Arc::new(RwLock::new(Instant::now()));
        tx.send_to(icmp_packet, target_ip)?;

        match iter.next() {
            Ok((packet, addr)) => match EchoReplyPacket::new(packet.packet()) {
                Some(echo_reply) => {
                    if packet.get_icmp_type() == IcmpTypes::EchoReply {
                        let start_time = timer.read().unwrap();
                        let rtt = Instant::now().duration_since(*start_time);
                        println!(
                            "ICMP EchoReply received from {:?}: {:?} , Time:{:?}, Identifier: {} => {}",
                            addr,
                            packet.get_icmp_type(),
                            rtt,
                            identifier,
                            echo_reply.get_identifier()
                        );
                    } else {
                        println!(
                            "ICMP type other than reply (0) received from {:?}: {:?}",
                            addr,
                            packet.get_icmp_type()
                        );
                    }
                }
                None => {}
            },
            Err(e) => {
                println!("An error occurred while reading: {}", e);
            }
        }

        std::thread::sleep(Duration::from_millis(500));
    }

    //Ok(())
}

fn create_icmp_packet<'a>(icmp_header: &'a mut [u8]) -> MutableEchoRequestPacket<'a> {
    let mut icmp_packet = MutableEchoRequestPacket::new(icmp_header).unwrap();
    icmp_packet.set_icmp_type(IcmpTypes::EchoRequest);
    icmp_packet.set_icmp_code(IcmpCodes::NoCode);
    icmp_packet.set_identifier(random::<u16>());
    icmp_packet.set_sequence_number(1);
    let checksum = util::checksum(icmp_packet.packet(), 1);
    icmp_packet.set_checksum(checksum);
    icmp_packet
}
`
