### ISSUE TITLE
a problem with the packet.lib configuration！help me.

### ISSUE THREAD

**Issue by fumenglin** [libpnet/libpnet#674]
error:
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\rustcrgFkNj\\symbols.o" "D:\\code\\rust\\dnsd\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-2889575c2b815479\\build_script_build-2889575c2b815479.build_script_build.6f7edc5701033128-cgu.0.rcgu.o" "D:\\code\\rust\\dnsd\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-2889575c2b815479\\build_script_build-2889575c2b815479.hmd9ckh8g7mdg2k.rcgu.o" "-L" "D:\\code\\rust\\dnsd\\target\\debug\\deps" "-L" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-2c326bf6d65382c9.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-63525e490005b6dd.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-7031d46f2b449e63.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libmemchr-0cf9f378388b0f47.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-2ee762450483d0d5.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-c690a34e7291ae3a.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-1b83e94b8977f939.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd_detect-e4e893023c10fff9.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-d595b957387b3e14.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-0026168964e7afa7.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libminiz_oxide-42f6b7d85036cc22.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libadler-8380b88fdaf0daa1.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-7614c4f9d3807285.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-12e574f92630833b.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-b3f93c3527b35687.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-2dc6ec96957b92ed.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-1ff4a7617c3cf002.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-1c55cc2662971b08.rlib" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-e7ee0456afea41c3.rlib" "-Wl,-Bdynamic" "-lkernel32" "-ladvapi32" "-lbcrypt" "-lkernel32" "-lntdll" "-luserenv" "-lws2_32" "-lkernel32" "-lws2_32" "-lkernel32" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "-Wl,--nxcompat" "-L" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-o" "D:\\code\\rust\\dnsd\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-2889575c2b815479\\build_script_build-2889575c2b815479.exe" "-Wl,--gc-sections" "-no-pie" "-nodefaultlibs" "D:\\soft\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          D:\code\rust\dnsd\target\debug\build\winapi-x86_64-pc-windows-gnu-2889575c2b815479\build_script_build-2889575c2b815479.build_script_build.6f7edc5701033128-cgu.0.rcgu.o:build_script_build:(.text+0xa4): undefined reference to `_Unwind_Resume'
          D:\code\rust\dnsd\target\debug\build\winapi-x86_64-pc-windows-gnu-2889575c2b815479\build_script_build-2889575c2b815479.build_script_build.6f7edc5701033128-cgu.0.rcgu.o:build_script_build:(.text+0x186): undefined reference to `_Unwind_Resume'
          D:\code\rust\dnsd\target\debug\build\winapi-x86_64-pc-windows-gnu-2889575c2b815479\build_script_build-2889575c2b815479.build_script_build.6f7edc5701033128-cgu.0.rcgu.o:build_script_build:(.text+0x40f): undefined reference to `_Unwind_Resume'
          D:\code\rust\dnsd\target\debug\build\winapi-x86_64-pc-windows-gnu-2889575c2b815479\build_script_build-2889575c2b815479.build_script_build.6f7edc5701033128-cgu.0.rcgu.o:build_script_build:(.text+0x4e9): undefined reference to `_Unwind_Resume'
          D:\code\rust\dnsd\target\debug\build\winapi-x86_64-pc-windows-gnu-2889575c2b815479\build_script_build-2889575c2b815479.build_script_build.6f7edc5701033128-cgu.0.rcgu.o:build_script_build:(.text+0x7bc): undefined reference to `_Unwind_Resume'
          D:\code\rust\dnsd\target\debug\build\winapi-x86_64-pc-windows-gnu-2889575c2b815479\build_script_build-2889575c2b815479.build_script_build.6f7edc5701033128-cgu.0.rcgu.o:build_script_build:(.text+0xddd): more undefined references to `_Unwind_Resume' follow
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libstd-2c326bf6d65382c9.rlib(std-2c326bf6d65382c9.std.8dc63118205ea875-cgu.0.rcgu.o): In function `rust_eh_personality':
          /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\personality/gcc.rs:248: undefined reference to `_GCC_specific_handler'
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libstd-2c326bf6d65382c9.rlib(std-2c326bf6d65382c9.std.8dc63118205ea875-cgu.0.rcgu.o): In function `<std::sys::windows::fs::DirBuffIter as core::iter::traits::iterator::Iterator>::next':
          /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows/fs.rs:796: undefined reference to `_Unwind_Resume'
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libstd-2c326bf6d65382c9.rlib(std-2c326bf6d65382c9.std.8dc63118205ea875-cgu.0.rcgu.o): In function `<std::sys::windows::fs::File as core::fmt::Debug>::fmt':
          /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows/fs.rs:913: undefined reference to `_Unwind_Resume'
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libstd-2c326bf6d65382c9.rlib(std-2c326bf6d65382c9.std.8dc63118205ea875-cgu.0.rcgu.o): In function `std::sys::windows::fs::readdir':
          /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows/fs.rs:1084: undefined reference to `_Unwind_Resume'
          /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows/fs.rs:1084: undefined reference to `_Unwind_Resume'
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libstd-2c326bf6d65382c9.rlib(std-2c326bf6d65382c9.std.8dc63118205ea875-cgu.0.rcgu.o): In function `std::sys::windows::fs::rename':
          /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows/fs.rs:1097: undefined reference to `_Unwind_Resume'
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libstd-2c326bf6d65382c9.rlib(std-2c326bf6d65382c9.std.8dc63118205ea875-cgu.0.rcgu.o):/rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows/fs.rs:1141: more undefined references to `_Unwind_Resume' follow
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libpanic_unwind-63525e490005b6dd.rlib(panic_unwind-63525e490005b6dd.panic_unwind.ba87ca4d116bb86b-cgu.0.rcgu.o): In function `panic_unwind::real_imp::panic':
          /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\panic_unwind\src/gcc.rs:72: undefined reference to `_Unwind_RaiseException'
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libpanic_unwind-63525e490005b6dd.rlib(panic_unwind-63525e490005b6dd.panic_unwind.ba87ca4d116bb86b-cgu.0.rcgu.o): In function `alloc::boxed::Box<T>::new':
          /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\alloc\src/boxed.rs:(.text+0x1fa): undefined reference to `_Unwind_Resume'
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libobject-7031d46f2b449e63.rlib(object-7031d46f2b449e63.object.7bc7c63129bfb8e9-cgu.0.rcgu.o):object.7bc7c63129b:(.text+0x1a77): undefined reference to `_Unwind_Resume'
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libobject-7031d46f2b449e63.rlib(object-7031d46f2b449e63.object.7bc7c63129bfb8e9-cgu.0.rcgu.o):object.7bc7c63129b:(.text+0x3f64): undefined reference to `_Unwind_Resume'
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libobject-7031d46f2b449e63.rlib(object-7031d46f2b449e63.object.7bc7c63129bfb8e9-cgu.0.rcgu.o):object.7bc7c63129b:(.text+0x5b47): undefined reference to `_Unwind_Resume'
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libobject-7031d46f2b449e63.rlib(object-7031d46f2b449e63.object.7bc7c63129bfb8e9-cgu.0.rcgu.o):object.7bc7c63129b:(.text+0x6750): undefined reference to `_Unwind_Resume'
          D:\soft\rust\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libgimli-c690a34e7291ae3a.rlib(gimli-c690a34e7291ae3a.gimli.8588f3b2bacbc4b-cgu.0.rcgu.o):gimli.8588f3b2bacb:(.text+0xcdf): more undefined references to `_Unwind_Resume' follow
          collect2.exe: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

It·s done：
![image](https://github.com/libpnet/libpnet/assets/15940670/46eeed93-3c7d-4cb4-bda1-4ff22946a0fa)

![image](https://github.com/libpnet/libpnet/assets/15940670/4cdc4127-622b-4a31-9b00-50b747e8d8b0)

Can anyone help me, thanks?

**Comment by fumenglin** [comment]
the MInGW use seh,do not use the sjlj.

**Comment by Martichou** [comment]
I don't have a direct answer, but can you reformat your post to add block code around the logs? It's not really easy to read right now. 

Can you also add the content of your `Cargo.toml`?

**Comment by fumenglin** [comment]
Thank you for your answer, now it's okay；The question is: the MInGW Should use seh。
