### ISSUE TITLE
Add TCP packet encoding/decoding

### ISSUE THREAD

**Issue by david415** [libpnet/libpnet#90]
Greetings. If it's OK with you I was thinking that this ticket could serve as an async comm channel alternative to `#libpnet`on IRC to discuss this feature addition.

**Comment by david415** [comment]
Here's my dev branch for this feature addition:
https://github.com/david415/libpnet/tree/90.add-tcp-packet.1

I've had some "working" commits... but the latest doesn't compile because of my incorrectly utilizing the variable length field; i've tried to implement this as described here:
https://github.com/libpnet/libpnet/pull/79#issue-88020109

```
#[packet]
pub struct Tcp {
    source: u16be,
    destination: u16be,
    sequence: u32be,
    acknowledgement: u32be,
    data_offset: u4,
    reserved: u4,
    control_bits: u8, // the first 5 bits are used; the rest is reserved
    window: u16be,
    checksum: u16be,
    urgent_pointer: u16be,
    #[length = "data_offset"]
    options: Vec<u32>,
    #[payload]
    payload: Vec<u8>
}
```

maybe the u4 fields prevent this from compiling?

**Comment by david415** [comment]
we also have some code here that is used to compose tcp/ip packets... with or without the ethernet header... although i did not get the layer3 linux raw socket transport to work yet.
https://github.com/david415/spray/blob/master/src/main.rs

**Comment by mrmonday** [comment]
Sorry I've taken so long to reply, I've been busy the past couple of days. I already replied on IRC, but I'll reply here for completeness.

The error you're getting:
```
src/packet/tcp.rs:32:5: 32:22 error: unimplemented variable length field
src/packet/tcp.rs:32     options: Vec<u32>,
                         ^~~~~~~~~~~~~~~~~
```
Is occurring because... well... I never implemented support for `Vec<u32>` in libpnet_macros. You have a couple of options here, either:
 * Add support for `Vec<u32>` in libpnet_macros.
 * Do what the IPv4 packet does, and use a separate packet type, see https://github.com/libpnet/libpnet/blob/master/src/packet/ipv4.rs#L36

Thank you for using libpnet!

**Comment by david415** [comment]
I got it to work! Now the Tcp struct has the optional variable length options field... and I've written unit tests that test this new functionality.

**Comment by david415** [comment]
The TCP header length must be on a 4 byte boundary. The mandatory header section is 20 bytes. After that the optional section is variable length. The last section of the header; the padding. This padding my only be utilized if the options section is not evenly divisible by 4 bytes.

Here's our complete TCP header:

```
#[packet]
pub struct Tcp {
    source: u16be,
    destination: u16be,
    sequence: u32be,
    acknowledgement: u32be,
    data_offset: u4,
    reserved: u4,
    control_bits: u8,
    window: u16be,
    checksum: u16be,
    urgent_pointer: u16be,
    #[length_fn = "tcp_options_length"]
    options: Vec<TcpOptions>,
    #[length_fn = "tcp_padding_length"]
    padding: Vec<TcpPadding>,
    #[payload]
    payload: Vec<u8>
}
```

The next thing that I need to do is write some helper functions to assist in TCP header composition... namely the user of this API would want helper functions like these :

- compute and set the checksum value
- an easy way to set various TCP header options
- automatic padding to 4 byte boundary if header options not evenly divisible by 4 bytes

**Comment by david415** [comment]
my latest work is in this dev branch https://github.com/david415/libpnet/tree/90.add-tcp-packet.1

It was easy to get my simple tcp header unit test to build and pass once I replaced the two u4 fields with a u8 field... now the tcp struct looks like this:

```
/// Represents a TCP Packet
#[packet]
pub struct Tcp {
    source: u16be,
    destination: u16be,
    sequence: u32be,
    acknowledgement: u32be,
    data_offset_and_reserved: u8,
    control_bits: u8,
    window: u16be,
    checksum: u16be,
    urgent_pointer: u16be,
    #[length_fn = "tcp_options_length"]
    options: Vec<TcpOptions>,
    #[length_fn = "tcp_padding_length"]
    padding: Vec<TcpPadding>,
    #[payload]
    payload: Vec<u8>
}
```

I think the next step is to finish this unit test by making it compute the TCP checksum using the new helper functions I wrote... and then after that I should write a IPv6 + TCP header unit test which also computes it's own checksum.

**Comment by david415** [comment]
currently this ticket is blocked on completing #91

**Comment by 2m** [comment]
I have rebased @david415 work in progress branch on to the latest master, for everyone wanting to try it out: https://github.com/2m/libpnet/tree/90.add-tcp-packet.1

**Comment by david415** [comment]
sweet!

**Comment by buckle2000** [comment]
Anyone still here?

**Comment by buckle2000** [comment]
Yes, libpnet can receive TCP packet, but how can I decode TCP packet from IP layer?

**Comment by david415** [comment]
if it works then good. done. converting from ethernet frames makes no sense. close ticket.

**Comment by mrmonday** [comment]
@buckle2000 You would take the `&[u8]` from the data link channel, construct an `EthernetPacket` from it. You can then construct either an IPv4 or IPv6 packet from the ethernet packet's payload, based on the ethertype. From there you can create your TCP packet, using the payload from the IP packet.
