### ISSUE TITLE
add rfc2460 ipv6 checksum function

### ISSUE THREAD

**Issue by david415** [libpnet/libpnet#92]
let it be known: i am volunteering to write this code.

The TCP checksum in a TCP/IPv6 packet uses the same rfc1071 checksum function but sets up the initial data differently. It's described in the rfc:
https://www.ietf.org/rfc/rfc2460.txt

This essentially means that the IPv6 pseudoheader for calculating the TCP checksum is necessarily different than the IPv4 pseudoheader... since the source and dest addresses in IPv6 are 128bit.

The rfc1071 checksum is based on addition and thus we should first calculate the pseudo-header checksum and then ADD to that with the rest of the TCP header checksum calculation. In this way we create good abstraction so that we reuse the same checksum function for all protocols... but have a differing preparatory step depending on the wrapping protocol (ipv4 versus ipv6).

gopacket's implementation is a good code reference:
https://github.com/google/gopacket/blob/master/layers/tcpip.go

This ticket is related to issue #90 tcp/ipv6.

**Comment by mrmonday** [comment]
Done in #244, I believe.
